/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as AuthForgetPasswordRouteImport } from './routes/_auth/forget-password'
import { Route as DashboardSettingsPageRouteImport } from './routes/dashboard/settings/page'
import { Route as DashboardLedgerPageRouteImport } from './routes/dashboard/ledger/page'
import { Route as DashboardCashManagementPageRouteImport } from './routes/dashboard/cash-management/page'
import { Route as DashboardAccountsReceivablePageRouteImport } from './routes/dashboard/accounts-receivable/page'
import { Route as DashboardAccountsPayablePageRouteImport } from './routes/dashboard/accounts-payable/page'
import { Route as DashboardhomePageRouteImport } from './routes/dashboard/(home)/page'
import { Route as PublichomePageRouteImport } from './routes/_public/(home)/page'
import { Route as AuthLoginPageRouteImport } from './routes/_auth/login/page'
import { Route as DashboardLedgerBatchLayoutRouteImport } from './routes/dashboard/ledger/batch/layout'
import { Route as DashboardCashManagementBatchLayoutRouteImport } from './routes/dashboard/cash-management/batch/layout'
import { Route as DashboardAccountsReceivableBatchLayoutRouteImport } from './routes/dashboard/accounts-receivable/batch/layout'
import { Route as DashboardAccountsPayableBatchLayoutRouteImport } from './routes/dashboard/accounts-payable/batch/layout'
import { Route as DashboardLedgerBatchPageRouteImport } from './routes/dashboard/ledger/batch/page'
import { Route as DashboardCashManagementBatchPageRouteImport } from './routes/dashboard/cash-management/batch/page'
import { Route as DashboardAccountsReceivableBatchPageRouteImport } from './routes/dashboard/accounts-receivable/batch/page'
import { Route as DashboardAccountsPayableBatchPageRouteImport } from './routes/dashboard/accounts-payable/batch/page'
import { Route as DashboardLedgerBatchBatchIdLayoutRouteImport } from './routes/dashboard/ledger/batch/$batchId/layout'
import { Route as DashboardCashManagementBatchBatchIdLayoutRouteImport } from './routes/dashboard/cash-management/batch/$batchId/layout'
import { Route as DashboardAccountsReceivableBatchBatchIdLayoutRouteImport } from './routes/dashboard/accounts-receivable/batch/$batchId/layout'
import { Route as DashboardAccountsPayableBatchBatchIdLayoutRouteImport } from './routes/dashboard/accounts-payable/batch/$batchId/layout'
import { Route as DashboardLedgerBatchNewPageRouteImport } from './routes/dashboard/ledger/batch/new/page'
import { Route as DashboardCashManagementBatchNewPageRouteImport } from './routes/dashboard/cash-management/batch/new/page'
import { Route as DashboardAccountsReceivableBatchNewPageRouteImport } from './routes/dashboard/accounts-receivable/batch/new/page'
import { Route as DashboardAccountsPayableBatchNewPageRouteImport } from './routes/dashboard/accounts-payable/batch/new/page'
import { Route as DashboardLedgerBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/ledger/batch/$batchId/errors/page'
import { Route as DashboardLedgerBatchBatchIdviewPageRouteImport } from './routes/dashboard/ledger/batch/$batchId/(view)/page'
import { Route as DashboardCashManagementBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/cash-management/batch/$batchId/errors/page'
import { Route as DashboardCashManagementBatchBatchIdviewPageRouteImport } from './routes/dashboard/cash-management/batch/$batchId/(view)/page'
import { Route as DashboardAccountsReceivableBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/accounts-receivable/batch/$batchId/errors/page'
import { Route as DashboardAccountsReceivableBatchBatchIdviewPageRouteImport } from './routes/dashboard/accounts-receivable/batch/$batchId/(view)/page'
import { Route as DashboardAccountsPayableBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/accounts-payable/batch/$batchId/errors/page'
import { Route as DashboardAccountsPayableBatchBatchIdviewPageRouteImport } from './routes/dashboard/accounts-payable/batch/$batchId/(view)/page'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardSettingsPageRoute = DashboardSettingsPageRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLedgerPageRoute = DashboardLedgerPageRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardCashManagementPageRoute =
  DashboardCashManagementPageRouteImport.update({
    id: '/cash-management/',
    path: '/cash-management/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAccountsReceivablePageRoute =
  DashboardAccountsReceivablePageRouteImport.update({
    id: '/accounts-receivable/',
    path: '/accounts-receivable/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAccountsPayablePageRoute =
  DashboardAccountsPayablePageRouteImport.update({
    id: '/accounts-payable/',
    path: '/accounts-payable/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardhomePageRoute = DashboardhomePageRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const PublichomePageRoute = PublichomePageRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthLoginPageRoute = AuthLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardLedgerBatchLayoutRoute =
  DashboardLedgerBatchLayoutRouteImport.update({
    id: '/ledger/batch',
    path: '/ledger/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardCashManagementBatchLayoutRoute =
  DashboardCashManagementBatchLayoutRouteImport.update({
    id: '/cash-management/batch',
    path: '/cash-management/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchLayoutRoute =
  DashboardAccountsReceivableBatchLayoutRouteImport.update({
    id: '/accounts-receivable/batch',
    path: '/accounts-receivable/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchLayoutRoute =
  DashboardAccountsPayableBatchLayoutRouteImport.update({
    id: '/accounts-payable/batch',
    path: '/accounts-payable/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLedgerBatchPageRoute =
  DashboardLedgerBatchPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLedgerBatchLayoutRoute,
  } as any)
const DashboardCashManagementBatchPageRoute =
  DashboardCashManagementBatchPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCashManagementBatchLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchPageRoute =
  DashboardAccountsReceivableBatchPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountsReceivableBatchLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchPageRoute =
  DashboardAccountsPayableBatchPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountsPayableBatchLayoutRoute,
  } as any)
const DashboardLedgerBatchBatchIdLayoutRoute =
  DashboardLedgerBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardLedgerBatchLayoutRoute,
  } as any)
const DashboardCashManagementBatchBatchIdLayoutRoute =
  DashboardCashManagementBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardCashManagementBatchLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchBatchIdLayoutRoute =
  DashboardAccountsReceivableBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardAccountsReceivableBatchLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchBatchIdLayoutRoute =
  DashboardAccountsPayableBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardAccountsPayableBatchLayoutRoute,
  } as any)
const DashboardLedgerBatchNewPageRoute =
  DashboardLedgerBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardLedgerBatchLayoutRoute,
  } as any)
const DashboardCashManagementBatchNewPageRoute =
  DashboardCashManagementBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardCashManagementBatchLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchNewPageRoute =
  DashboardAccountsReceivableBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardAccountsReceivableBatchLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchNewPageRoute =
  DashboardAccountsPayableBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardAccountsPayableBatchLayoutRoute,
  } as any)
const DashboardLedgerBatchBatchIdErrorsPageRoute =
  DashboardLedgerBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardLedgerBatchBatchIdLayoutRoute,
  } as any)
const DashboardLedgerBatchBatchIdviewPageRoute =
  DashboardLedgerBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardLedgerBatchBatchIdLayoutRoute,
  } as any)
const DashboardCashManagementBatchBatchIdErrorsPageRoute =
  DashboardCashManagementBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardCashManagementBatchBatchIdLayoutRoute,
  } as any)
const DashboardCashManagementBatchBatchIdviewPageRoute =
  DashboardCashManagementBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardCashManagementBatchBatchIdLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchBatchIdErrorsPageRoute =
  DashboardAccountsReceivableBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardAccountsReceivableBatchBatchIdLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchBatchIdviewPageRoute =
  DashboardAccountsReceivableBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardAccountsReceivableBatchBatchIdLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchBatchIdErrorsPageRoute =
  DashboardAccountsPayableBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardAccountsPayableBatchBatchIdLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchBatchIdviewPageRoute =
  DashboardAccountsPayableBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardAccountsPayableBatchBatchIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/forget-password': typeof AuthForgetPasswordRoute
  '/dashboard/accounts-payable/batch': typeof DashboardAccountsPayableBatchLayoutRouteWithChildren
  '/dashboard/accounts-receivable/batch': typeof DashboardAccountsReceivableBatchLayoutRouteWithChildren
  '/dashboard/cash-management/batch': typeof DashboardCashManagementBatchLayoutRouteWithChildren
  '/dashboard/ledger/batch': typeof DashboardLedgerBatchLayoutRouteWithChildren
  '/login': typeof AuthLoginPageRoute
  '/': typeof PublichomePageRoute
  '/dashboard/': typeof DashboardhomePageRoute
  '/dashboard/accounts-payable': typeof DashboardAccountsPayablePageRoute
  '/dashboard/accounts-receivable': typeof DashboardAccountsReceivablePageRoute
  '/dashboard/cash-management': typeof DashboardCashManagementPageRoute
  '/dashboard/ledger': typeof DashboardLedgerPageRoute
  '/dashboard/settings': typeof DashboardSettingsPageRoute
  '/dashboard/accounts-payable/batch/$batchId': typeof DashboardAccountsPayableBatchBatchIdLayoutRouteWithChildren
  '/dashboard/accounts-receivable/batch/$batchId': typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren
  '/dashboard/cash-management/batch/$batchId': typeof DashboardCashManagementBatchBatchIdLayoutRouteWithChildren
  '/dashboard/ledger/batch/$batchId': typeof DashboardLedgerBatchBatchIdLayoutRouteWithChildren
  '/dashboard/accounts-payable/batch/': typeof DashboardAccountsPayableBatchPageRoute
  '/dashboard/accounts-receivable/batch/': typeof DashboardAccountsReceivableBatchPageRoute
  '/dashboard/cash-management/batch/': typeof DashboardCashManagementBatchPageRoute
  '/dashboard/ledger/batch/': typeof DashboardLedgerBatchPageRoute
  '/dashboard/accounts-payable/batch/new': typeof DashboardAccountsPayableBatchNewPageRoute
  '/dashboard/accounts-receivable/batch/new': typeof DashboardAccountsReceivableBatchNewPageRoute
  '/dashboard/cash-management/batch/new': typeof DashboardCashManagementBatchNewPageRoute
  '/dashboard/ledger/batch/new': typeof DashboardLedgerBatchNewPageRoute
  '/dashboard/accounts-payable/batch/$batchId/': typeof DashboardAccountsPayableBatchBatchIdviewPageRoute
  '/dashboard/accounts-payable/batch/$batchId/errors': typeof DashboardAccountsPayableBatchBatchIdErrorsPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/': typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/errors': typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
  '/dashboard/cash-management/batch/$batchId/': typeof DashboardCashManagementBatchBatchIdviewPageRoute
  '/dashboard/cash-management/batch/$batchId/errors': typeof DashboardCashManagementBatchBatchIdErrorsPageRoute
  '/dashboard/ledger/batch/$batchId/': typeof DashboardLedgerBatchBatchIdviewPageRoute
  '/dashboard/ledger/batch/$batchId/errors': typeof DashboardLedgerBatchBatchIdErrorsPageRoute
}
export interface FileRoutesByTo {
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginPageRoute
  '/': typeof PublichomePageRoute
  '/dashboard': typeof DashboardhomePageRoute
  '/dashboard/accounts-payable': typeof DashboardAccountsPayablePageRoute
  '/dashboard/accounts-receivable': typeof DashboardAccountsReceivablePageRoute
  '/dashboard/cash-management': typeof DashboardCashManagementPageRoute
  '/dashboard/ledger': typeof DashboardLedgerPageRoute
  '/dashboard/settings': typeof DashboardSettingsPageRoute
  '/dashboard/accounts-payable/batch': typeof DashboardAccountsPayableBatchPageRoute
  '/dashboard/accounts-receivable/batch': typeof DashboardAccountsReceivableBatchPageRoute
  '/dashboard/cash-management/batch': typeof DashboardCashManagementBatchPageRoute
  '/dashboard/ledger/batch': typeof DashboardLedgerBatchPageRoute
  '/dashboard/accounts-payable/batch/new': typeof DashboardAccountsPayableBatchNewPageRoute
  '/dashboard/accounts-receivable/batch/new': typeof DashboardAccountsReceivableBatchNewPageRoute
  '/dashboard/cash-management/batch/new': typeof DashboardCashManagementBatchNewPageRoute
  '/dashboard/ledger/batch/new': typeof DashboardLedgerBatchNewPageRoute
  '/dashboard/accounts-payable/batch/$batchId': typeof DashboardAccountsPayableBatchBatchIdviewPageRoute
  '/dashboard/accounts-payable/batch/$batchId/errors': typeof DashboardAccountsPayableBatchBatchIdErrorsPageRoute
  '/dashboard/accounts-receivable/batch/$batchId': typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/errors': typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
  '/dashboard/cash-management/batch/$batchId': typeof DashboardCashManagementBatchBatchIdviewPageRoute
  '/dashboard/cash-management/batch/$batchId/errors': typeof DashboardCashManagementBatchBatchIdErrorsPageRoute
  '/dashboard/ledger/batch/$batchId': typeof DashboardLedgerBatchBatchIdviewPageRoute
  '/dashboard/ledger/batch/$batchId/errors': typeof DashboardLedgerBatchBatchIdErrorsPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/_auth/forget-password': typeof AuthForgetPasswordRoute
  '/dashboard/accounts-payable/batch': typeof DashboardAccountsPayableBatchLayoutRouteWithChildren
  '/dashboard/accounts-receivable/batch': typeof DashboardAccountsReceivableBatchLayoutRouteWithChildren
  '/dashboard/cash-management/batch': typeof DashboardCashManagementBatchLayoutRouteWithChildren
  '/dashboard/ledger/batch': typeof DashboardLedgerBatchLayoutRouteWithChildren
  '/_auth/login/': typeof AuthLoginPageRoute
  '/_public/(home)/': typeof PublichomePageRoute
  '/dashboard/(home)/': typeof DashboardhomePageRoute
  '/dashboard/accounts-payable/': typeof DashboardAccountsPayablePageRoute
  '/dashboard/accounts-receivable/': typeof DashboardAccountsReceivablePageRoute
  '/dashboard/cash-management/': typeof DashboardCashManagementPageRoute
  '/dashboard/ledger/': typeof DashboardLedgerPageRoute
  '/dashboard/settings/': typeof DashboardSettingsPageRoute
  '/dashboard/accounts-payable/batch/$batchId': typeof DashboardAccountsPayableBatchBatchIdLayoutRouteWithChildren
  '/dashboard/accounts-receivable/batch/$batchId': typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren
  '/dashboard/cash-management/batch/$batchId': typeof DashboardCashManagementBatchBatchIdLayoutRouteWithChildren
  '/dashboard/ledger/batch/$batchId': typeof DashboardLedgerBatchBatchIdLayoutRouteWithChildren
  '/dashboard/accounts-payable/batch/': typeof DashboardAccountsPayableBatchPageRoute
  '/dashboard/accounts-receivable/batch/': typeof DashboardAccountsReceivableBatchPageRoute
  '/dashboard/cash-management/batch/': typeof DashboardCashManagementBatchPageRoute
  '/dashboard/ledger/batch/': typeof DashboardLedgerBatchPageRoute
  '/dashboard/accounts-payable/batch/new/': typeof DashboardAccountsPayableBatchNewPageRoute
  '/dashboard/accounts-receivable/batch/new/': typeof DashboardAccountsReceivableBatchNewPageRoute
  '/dashboard/cash-management/batch/new/': typeof DashboardCashManagementBatchNewPageRoute
  '/dashboard/ledger/batch/new/': typeof DashboardLedgerBatchNewPageRoute
  '/dashboard/accounts-payable/batch/$batchId/(view)/': typeof DashboardAccountsPayableBatchBatchIdviewPageRoute
  '/dashboard/accounts-payable/batch/$batchId/errors/': typeof DashboardAccountsPayableBatchBatchIdErrorsPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/(view)/': typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/errors/': typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
  '/dashboard/cash-management/batch/$batchId/(view)/': typeof DashboardCashManagementBatchBatchIdviewPageRoute
  '/dashboard/cash-management/batch/$batchId/errors/': typeof DashboardCashManagementBatchBatchIdErrorsPageRoute
  '/dashboard/ledger/batch/$batchId/(view)/': typeof DashboardLedgerBatchBatchIdviewPageRoute
  '/dashboard/ledger/batch/$batchId/errors/': typeof DashboardLedgerBatchBatchIdErrorsPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/forget-password'
    | '/dashboard/accounts-payable/batch'
    | '/dashboard/accounts-receivable/batch'
    | '/dashboard/cash-management/batch'
    | '/dashboard/ledger/batch'
    | '/login'
    | '/'
    | '/dashboard/'
    | '/dashboard/accounts-payable'
    | '/dashboard/accounts-receivable'
    | '/dashboard/cash-management'
    | '/dashboard/ledger'
    | '/dashboard/settings'
    | '/dashboard/accounts-payable/batch/$batchId'
    | '/dashboard/accounts-receivable/batch/$batchId'
    | '/dashboard/cash-management/batch/$batchId'
    | '/dashboard/ledger/batch/$batchId'
    | '/dashboard/accounts-payable/batch/'
    | '/dashboard/accounts-receivable/batch/'
    | '/dashboard/cash-management/batch/'
    | '/dashboard/ledger/batch/'
    | '/dashboard/accounts-payable/batch/new'
    | '/dashboard/accounts-receivable/batch/new'
    | '/dashboard/cash-management/batch/new'
    | '/dashboard/ledger/batch/new'
    | '/dashboard/accounts-payable/batch/$batchId/'
    | '/dashboard/accounts-payable/batch/$batchId/errors'
    | '/dashboard/accounts-receivable/batch/$batchId/'
    | '/dashboard/accounts-receivable/batch/$batchId/errors'
    | '/dashboard/cash-management/batch/$batchId/'
    | '/dashboard/cash-management/batch/$batchId/errors'
    | '/dashboard/ledger/batch/$batchId/'
    | '/dashboard/ledger/batch/$batchId/errors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forget-password'
    | '/login'
    | '/'
    | '/dashboard'
    | '/dashboard/accounts-payable'
    | '/dashboard/accounts-receivable'
    | '/dashboard/cash-management'
    | '/dashboard/ledger'
    | '/dashboard/settings'
    | '/dashboard/accounts-payable/batch'
    | '/dashboard/accounts-receivable/batch'
    | '/dashboard/cash-management/batch'
    | '/dashboard/ledger/batch'
    | '/dashboard/accounts-payable/batch/new'
    | '/dashboard/accounts-receivable/batch/new'
    | '/dashboard/cash-management/batch/new'
    | '/dashboard/ledger/batch/new'
    | '/dashboard/accounts-payable/batch/$batchId'
    | '/dashboard/accounts-payable/batch/$batchId/errors'
    | '/dashboard/accounts-receivable/batch/$batchId'
    | '/dashboard/accounts-receivable/batch/$batchId/errors'
    | '/dashboard/cash-management/batch/$batchId'
    | '/dashboard/cash-management/batch/$batchId/errors'
    | '/dashboard/ledger/batch/$batchId'
    | '/dashboard/ledger/batch/$batchId/errors'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/dashboard'
    | '/_auth/forget-password'
    | '/dashboard/accounts-payable/batch'
    | '/dashboard/accounts-receivable/batch'
    | '/dashboard/cash-management/batch'
    | '/dashboard/ledger/batch'
    | '/_auth/login/'
    | '/_public/(home)/'
    | '/dashboard/(home)/'
    | '/dashboard/accounts-payable/'
    | '/dashboard/accounts-receivable/'
    | '/dashboard/cash-management/'
    | '/dashboard/ledger/'
    | '/dashboard/settings/'
    | '/dashboard/accounts-payable/batch/$batchId'
    | '/dashboard/accounts-receivable/batch/$batchId'
    | '/dashboard/cash-management/batch/$batchId'
    | '/dashboard/ledger/batch/$batchId'
    | '/dashboard/accounts-payable/batch/'
    | '/dashboard/accounts-receivable/batch/'
    | '/dashboard/cash-management/batch/'
    | '/dashboard/ledger/batch/'
    | '/dashboard/accounts-payable/batch/new/'
    | '/dashboard/accounts-receivable/batch/new/'
    | '/dashboard/cash-management/batch/new/'
    | '/dashboard/ledger/batch/new/'
    | '/dashboard/accounts-payable/batch/$batchId/(view)/'
    | '/dashboard/accounts-payable/batch/$batchId/errors/'
    | '/dashboard/accounts-receivable/batch/$batchId/(view)/'
    | '/dashboard/accounts-receivable/batch/$batchId/errors/'
    | '/dashboard/cash-management/batch/$batchId/(view)/'
    | '/dashboard/cash-management/batch/$batchId/errors/'
    | '/dashboard/ledger/batch/$batchId/(view)/'
    | '/dashboard/ledger/batch/$batchId/errors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forget-password': {
      id: '/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsPageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/ledger/': {
      id: '/dashboard/ledger/'
      path: '/ledger'
      fullPath: '/dashboard/ledger'
      preLoaderRoute: typeof DashboardLedgerPageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/cash-management/': {
      id: '/dashboard/cash-management/'
      path: '/cash-management'
      fullPath: '/dashboard/cash-management'
      preLoaderRoute: typeof DashboardCashManagementPageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/accounts-receivable/': {
      id: '/dashboard/accounts-receivable/'
      path: '/accounts-receivable'
      fullPath: '/dashboard/accounts-receivable'
      preLoaderRoute: typeof DashboardAccountsReceivablePageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/accounts-payable/': {
      id: '/dashboard/accounts-payable/'
      path: '/accounts-payable'
      fullPath: '/dashboard/accounts-payable'
      preLoaderRoute: typeof DashboardAccountsPayablePageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/(home)/': {
      id: '/dashboard/(home)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardhomePageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_public/(home)/': {
      id: '/_public/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublichomePageRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/ledger/batch': {
      id: '/dashboard/ledger/batch'
      path: '/ledger/batch'
      fullPath: '/dashboard/ledger/batch'
      preLoaderRoute: typeof DashboardLedgerBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/cash-management/batch': {
      id: '/dashboard/cash-management/batch'
      path: '/cash-management/batch'
      fullPath: '/dashboard/cash-management/batch'
      preLoaderRoute: typeof DashboardCashManagementBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/accounts-receivable/batch': {
      id: '/dashboard/accounts-receivable/batch'
      path: '/accounts-receivable/batch'
      fullPath: '/dashboard/accounts-receivable/batch'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/accounts-payable/batch': {
      id: '/dashboard/accounts-payable/batch'
      path: '/accounts-payable/batch'
      fullPath: '/dashboard/accounts-payable/batch'
      preLoaderRoute: typeof DashboardAccountsPayableBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/ledger/batch/': {
      id: '/dashboard/ledger/batch/'
      path: '/'
      fullPath: '/dashboard/ledger/batch/'
      preLoaderRoute: typeof DashboardLedgerBatchPageRouteImport
      parentRoute: typeof DashboardLedgerBatchLayoutRoute
    }
    '/dashboard/cash-management/batch/': {
      id: '/dashboard/cash-management/batch/'
      path: '/'
      fullPath: '/dashboard/cash-management/batch/'
      preLoaderRoute: typeof DashboardCashManagementBatchPageRouteImport
      parentRoute: typeof DashboardCashManagementBatchLayoutRoute
    }
    '/dashboard/accounts-receivable/batch/': {
      id: '/dashboard/accounts-receivable/batch/'
      path: '/'
      fullPath: '/dashboard/accounts-receivable/batch/'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchPageRouteImport
      parentRoute: typeof DashboardAccountsReceivableBatchLayoutRoute
    }
    '/dashboard/accounts-payable/batch/': {
      id: '/dashboard/accounts-payable/batch/'
      path: '/'
      fullPath: '/dashboard/accounts-payable/batch/'
      preLoaderRoute: typeof DashboardAccountsPayableBatchPageRouteImport
      parentRoute: typeof DashboardAccountsPayableBatchLayoutRoute
    }
    '/dashboard/ledger/batch/$batchId': {
      id: '/dashboard/ledger/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/ledger/batch/$batchId'
      preLoaderRoute: typeof DashboardLedgerBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardLedgerBatchLayoutRoute
    }
    '/dashboard/cash-management/batch/$batchId': {
      id: '/dashboard/cash-management/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/cash-management/batch/$batchId'
      preLoaderRoute: typeof DashboardCashManagementBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardCashManagementBatchLayoutRoute
    }
    '/dashboard/accounts-receivable/batch/$batchId': {
      id: '/dashboard/accounts-receivable/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/accounts-receivable/batch/$batchId'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardAccountsReceivableBatchLayoutRoute
    }
    '/dashboard/accounts-payable/batch/$batchId': {
      id: '/dashboard/accounts-payable/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/accounts-payable/batch/$batchId'
      preLoaderRoute: typeof DashboardAccountsPayableBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardAccountsPayableBatchLayoutRoute
    }
    '/dashboard/ledger/batch/new/': {
      id: '/dashboard/ledger/batch/new/'
      path: '/new'
      fullPath: '/dashboard/ledger/batch/new'
      preLoaderRoute: typeof DashboardLedgerBatchNewPageRouteImport
      parentRoute: typeof DashboardLedgerBatchLayoutRoute
    }
    '/dashboard/cash-management/batch/new/': {
      id: '/dashboard/cash-management/batch/new/'
      path: '/new'
      fullPath: '/dashboard/cash-management/batch/new'
      preLoaderRoute: typeof DashboardCashManagementBatchNewPageRouteImport
      parentRoute: typeof DashboardCashManagementBatchLayoutRoute
    }
    '/dashboard/accounts-receivable/batch/new/': {
      id: '/dashboard/accounts-receivable/batch/new/'
      path: '/new'
      fullPath: '/dashboard/accounts-receivable/batch/new'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchNewPageRouteImport
      parentRoute: typeof DashboardAccountsReceivableBatchLayoutRoute
    }
    '/dashboard/accounts-payable/batch/new/': {
      id: '/dashboard/accounts-payable/batch/new/'
      path: '/new'
      fullPath: '/dashboard/accounts-payable/batch/new'
      preLoaderRoute: typeof DashboardAccountsPayableBatchNewPageRouteImport
      parentRoute: typeof DashboardAccountsPayableBatchLayoutRoute
    }
    '/dashboard/ledger/batch/$batchId/errors/': {
      id: '/dashboard/ledger/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/ledger/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardLedgerBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardLedgerBatchBatchIdLayoutRoute
    }
    '/dashboard/ledger/batch/$batchId/(view)/': {
      id: '/dashboard/ledger/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/ledger/batch/$batchId/'
      preLoaderRoute: typeof DashboardLedgerBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardLedgerBatchBatchIdLayoutRoute
    }
    '/dashboard/cash-management/batch/$batchId/errors/': {
      id: '/dashboard/cash-management/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/cash-management/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardCashManagementBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardCashManagementBatchBatchIdLayoutRoute
    }
    '/dashboard/cash-management/batch/$batchId/(view)/': {
      id: '/dashboard/cash-management/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/cash-management/batch/$batchId/'
      preLoaderRoute: typeof DashboardCashManagementBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardCashManagementBatchBatchIdLayoutRoute
    }
    '/dashboard/accounts-receivable/batch/$batchId/errors/': {
      id: '/dashboard/accounts-receivable/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/accounts-receivable/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutRoute
    }
    '/dashboard/accounts-receivable/batch/$batchId/(view)/': {
      id: '/dashboard/accounts-receivable/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/accounts-receivable/batch/$batchId/'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutRoute
    }
    '/dashboard/accounts-payable/batch/$batchId/errors/': {
      id: '/dashboard/accounts-payable/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/accounts-payable/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardAccountsPayableBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardAccountsPayableBatchBatchIdLayoutRoute
    }
    '/dashboard/accounts-payable/batch/$batchId/(view)/': {
      id: '/dashboard/accounts-payable/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/accounts-payable/batch/$batchId/'
      preLoaderRoute: typeof DashboardAccountsPayableBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardAccountsPayableBatchBatchIdLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginPageRoute: typeof AuthLoginPageRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginPageRoute: AuthLoginPageRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublichomePageRoute: typeof PublichomePageRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublichomePageRoute: PublichomePageRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface DashboardAccountsPayableBatchBatchIdLayoutRouteChildren {
  DashboardAccountsPayableBatchBatchIdviewPageRoute: typeof DashboardAccountsPayableBatchBatchIdviewPageRoute
  DashboardAccountsPayableBatchBatchIdErrorsPageRoute: typeof DashboardAccountsPayableBatchBatchIdErrorsPageRoute
}

const DashboardAccountsPayableBatchBatchIdLayoutRouteChildren: DashboardAccountsPayableBatchBatchIdLayoutRouteChildren =
  {
    DashboardAccountsPayableBatchBatchIdviewPageRoute:
      DashboardAccountsPayableBatchBatchIdviewPageRoute,
    DashboardAccountsPayableBatchBatchIdErrorsPageRoute:
      DashboardAccountsPayableBatchBatchIdErrorsPageRoute,
  }

const DashboardAccountsPayableBatchBatchIdLayoutRouteWithChildren =
  DashboardAccountsPayableBatchBatchIdLayoutRoute._addFileChildren(
    DashboardAccountsPayableBatchBatchIdLayoutRouteChildren,
  )

interface DashboardAccountsPayableBatchLayoutRouteChildren {
  DashboardAccountsPayableBatchBatchIdLayoutRoute: typeof DashboardAccountsPayableBatchBatchIdLayoutRouteWithChildren
  DashboardAccountsPayableBatchPageRoute: typeof DashboardAccountsPayableBatchPageRoute
  DashboardAccountsPayableBatchNewPageRoute: typeof DashboardAccountsPayableBatchNewPageRoute
}

const DashboardAccountsPayableBatchLayoutRouteChildren: DashboardAccountsPayableBatchLayoutRouteChildren =
  {
    DashboardAccountsPayableBatchBatchIdLayoutRoute:
      DashboardAccountsPayableBatchBatchIdLayoutRouteWithChildren,
    DashboardAccountsPayableBatchPageRoute:
      DashboardAccountsPayableBatchPageRoute,
    DashboardAccountsPayableBatchNewPageRoute:
      DashboardAccountsPayableBatchNewPageRoute,
  }

const DashboardAccountsPayableBatchLayoutRouteWithChildren =
  DashboardAccountsPayableBatchLayoutRoute._addFileChildren(
    DashboardAccountsPayableBatchLayoutRouteChildren,
  )

interface DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren {
  DashboardAccountsReceivableBatchBatchIdviewPageRoute: typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  DashboardAccountsReceivableBatchBatchIdErrorsPageRoute: typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
}

const DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren: DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren =
  {
    DashboardAccountsReceivableBatchBatchIdviewPageRoute:
      DashboardAccountsReceivableBatchBatchIdviewPageRoute,
    DashboardAccountsReceivableBatchBatchIdErrorsPageRoute:
      DashboardAccountsReceivableBatchBatchIdErrorsPageRoute,
  }

const DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren =
  DashboardAccountsReceivableBatchBatchIdLayoutRoute._addFileChildren(
    DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren,
  )

interface DashboardAccountsReceivableBatchLayoutRouteChildren {
  DashboardAccountsReceivableBatchBatchIdLayoutRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren
  DashboardAccountsReceivableBatchPageRoute: typeof DashboardAccountsReceivableBatchPageRoute
  DashboardAccountsReceivableBatchNewPageRoute: typeof DashboardAccountsReceivableBatchNewPageRoute
}

const DashboardAccountsReceivableBatchLayoutRouteChildren: DashboardAccountsReceivableBatchLayoutRouteChildren =
  {
    DashboardAccountsReceivableBatchBatchIdLayoutRoute:
      DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren,
    DashboardAccountsReceivableBatchPageRoute:
      DashboardAccountsReceivableBatchPageRoute,
    DashboardAccountsReceivableBatchNewPageRoute:
      DashboardAccountsReceivableBatchNewPageRoute,
  }

const DashboardAccountsReceivableBatchLayoutRouteWithChildren =
  DashboardAccountsReceivableBatchLayoutRoute._addFileChildren(
    DashboardAccountsReceivableBatchLayoutRouteChildren,
  )

interface DashboardCashManagementBatchBatchIdLayoutRouteChildren {
  DashboardCashManagementBatchBatchIdviewPageRoute: typeof DashboardCashManagementBatchBatchIdviewPageRoute
  DashboardCashManagementBatchBatchIdErrorsPageRoute: typeof DashboardCashManagementBatchBatchIdErrorsPageRoute
}

const DashboardCashManagementBatchBatchIdLayoutRouteChildren: DashboardCashManagementBatchBatchIdLayoutRouteChildren =
  {
    DashboardCashManagementBatchBatchIdviewPageRoute:
      DashboardCashManagementBatchBatchIdviewPageRoute,
    DashboardCashManagementBatchBatchIdErrorsPageRoute:
      DashboardCashManagementBatchBatchIdErrorsPageRoute,
  }

const DashboardCashManagementBatchBatchIdLayoutRouteWithChildren =
  DashboardCashManagementBatchBatchIdLayoutRoute._addFileChildren(
    DashboardCashManagementBatchBatchIdLayoutRouteChildren,
  )

interface DashboardCashManagementBatchLayoutRouteChildren {
  DashboardCashManagementBatchBatchIdLayoutRoute: typeof DashboardCashManagementBatchBatchIdLayoutRouteWithChildren
  DashboardCashManagementBatchPageRoute: typeof DashboardCashManagementBatchPageRoute
  DashboardCashManagementBatchNewPageRoute: typeof DashboardCashManagementBatchNewPageRoute
}

const DashboardCashManagementBatchLayoutRouteChildren: DashboardCashManagementBatchLayoutRouteChildren =
  {
    DashboardCashManagementBatchBatchIdLayoutRoute:
      DashboardCashManagementBatchBatchIdLayoutRouteWithChildren,
    DashboardCashManagementBatchPageRoute:
      DashboardCashManagementBatchPageRoute,
    DashboardCashManagementBatchNewPageRoute:
      DashboardCashManagementBatchNewPageRoute,
  }

const DashboardCashManagementBatchLayoutRouteWithChildren =
  DashboardCashManagementBatchLayoutRoute._addFileChildren(
    DashboardCashManagementBatchLayoutRouteChildren,
  )

interface DashboardLedgerBatchBatchIdLayoutRouteChildren {
  DashboardLedgerBatchBatchIdviewPageRoute: typeof DashboardLedgerBatchBatchIdviewPageRoute
  DashboardLedgerBatchBatchIdErrorsPageRoute: typeof DashboardLedgerBatchBatchIdErrorsPageRoute
}

const DashboardLedgerBatchBatchIdLayoutRouteChildren: DashboardLedgerBatchBatchIdLayoutRouteChildren =
  {
    DashboardLedgerBatchBatchIdviewPageRoute:
      DashboardLedgerBatchBatchIdviewPageRoute,
    DashboardLedgerBatchBatchIdErrorsPageRoute:
      DashboardLedgerBatchBatchIdErrorsPageRoute,
  }

const DashboardLedgerBatchBatchIdLayoutRouteWithChildren =
  DashboardLedgerBatchBatchIdLayoutRoute._addFileChildren(
    DashboardLedgerBatchBatchIdLayoutRouteChildren,
  )

interface DashboardLedgerBatchLayoutRouteChildren {
  DashboardLedgerBatchBatchIdLayoutRoute: typeof DashboardLedgerBatchBatchIdLayoutRouteWithChildren
  DashboardLedgerBatchPageRoute: typeof DashboardLedgerBatchPageRoute
  DashboardLedgerBatchNewPageRoute: typeof DashboardLedgerBatchNewPageRoute
}

const DashboardLedgerBatchLayoutRouteChildren: DashboardLedgerBatchLayoutRouteChildren =
  {
    DashboardLedgerBatchBatchIdLayoutRoute:
      DashboardLedgerBatchBatchIdLayoutRouteWithChildren,
    DashboardLedgerBatchPageRoute: DashboardLedgerBatchPageRoute,
    DashboardLedgerBatchNewPageRoute: DashboardLedgerBatchNewPageRoute,
  }

const DashboardLedgerBatchLayoutRouteWithChildren =
  DashboardLedgerBatchLayoutRoute._addFileChildren(
    DashboardLedgerBatchLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardAccountsPayableBatchLayoutRoute: typeof DashboardAccountsPayableBatchLayoutRouteWithChildren
  DashboardAccountsReceivableBatchLayoutRoute: typeof DashboardAccountsReceivableBatchLayoutRouteWithChildren
  DashboardCashManagementBatchLayoutRoute: typeof DashboardCashManagementBatchLayoutRouteWithChildren
  DashboardLedgerBatchLayoutRoute: typeof DashboardLedgerBatchLayoutRouteWithChildren
  DashboardhomePageRoute: typeof DashboardhomePageRoute
  DashboardAccountsPayablePageRoute: typeof DashboardAccountsPayablePageRoute
  DashboardAccountsReceivablePageRoute: typeof DashboardAccountsReceivablePageRoute
  DashboardCashManagementPageRoute: typeof DashboardCashManagementPageRoute
  DashboardLedgerPageRoute: typeof DashboardLedgerPageRoute
  DashboardSettingsPageRoute: typeof DashboardSettingsPageRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardAccountsPayableBatchLayoutRoute:
    DashboardAccountsPayableBatchLayoutRouteWithChildren,
  DashboardAccountsReceivableBatchLayoutRoute:
    DashboardAccountsReceivableBatchLayoutRouteWithChildren,
  DashboardCashManagementBatchLayoutRoute:
    DashboardCashManagementBatchLayoutRouteWithChildren,
  DashboardLedgerBatchLayoutRoute: DashboardLedgerBatchLayoutRouteWithChildren,
  DashboardhomePageRoute: DashboardhomePageRoute,
  DashboardAccountsPayablePageRoute: DashboardAccountsPayablePageRoute,
  DashboardAccountsReceivablePageRoute: DashboardAccountsReceivablePageRoute,
  DashboardCashManagementPageRoute: DashboardCashManagementPageRoute,
  DashboardLedgerPageRoute: DashboardLedgerPageRoute,
  DashboardSettingsPageRoute: DashboardSettingsPageRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
