/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardLayoutImport } from './routes/dashboard/layout'
import { Route as PublicLayoutImport } from './routes/_public/layout'
import { Route as AuthLayoutImport } from './routes/_auth/layout'
import { Route as AuthForgetPasswordImport } from './routes/_auth/forget-password'
import { Route as DashboardSettingsPageImport } from './routes/dashboard/settings/page'
import { Route as DashboardCashManagementPageImport } from './routes/dashboard/cash-management/page'
import { Route as DashboardAccountsReceivablePageImport } from './routes/dashboard/accounts-receivable/page'
import { Route as DashboardAccountsPayablePageImport } from './routes/dashboard/accounts-payable/page'
import { Route as DashboardhomePageImport } from './routes/dashboard/(home)/page'
import { Route as PublichomePageImport } from './routes/_public/(home)/page'
import { Route as AuthLoginPageImport } from './routes/_auth/login/page'
import { Route as DashboardAccountsReceivableBatchPageImport } from './routes/dashboard/accounts-receivable/batch/page'
import { Route as DashboardAccountsReceivableBatchBatchIdLayoutImport } from './routes/dashboard/accounts-receivable/batch/$batchId/layout'
import { Route as DashboardAccountsReceivableBatchNewPageImport } from './routes/dashboard/accounts-receivable/batch/new/page'
import { Route as DashboardAccountsReceivableBatchBatchIdErrorsPageImport } from './routes/dashboard/accounts-receivable/batch/$batchId/errors/page'
import { Route as DashboardAccountsReceivableBatchBatchIdviewPageImport } from './routes/dashboard/accounts-receivable/batch/$batchId/(view)/page'

// Create/Update Routes

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const PublicLayoutRoute = PublicLayoutImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgetPasswordRoute = AuthForgetPasswordImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const DashboardSettingsPageRoute = DashboardSettingsPageImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardCashManagementPageRoute =
  DashboardCashManagementPageImport.update({
    id: '/cash-management/',
    path: '/cash-management/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardAccountsReceivablePageRoute =
  DashboardAccountsReceivablePageImport.update({
    id: '/accounts-receivable/',
    path: '/accounts-receivable/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardAccountsPayablePageRoute =
  DashboardAccountsPayablePageImport.update({
    id: '/accounts-payable/',
    path: '/accounts-payable/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardhomePageRoute = DashboardhomePageImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const PublichomePageRoute = PublichomePageImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const AuthLoginPageRoute = AuthLoginPageImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const DashboardAccountsReceivableBatchPageRoute =
  DashboardAccountsReceivableBatchPageImport.update({
    id: '/accounts-receivable/batch/',
    path: '/accounts-receivable/batch/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardAccountsReceivableBatchBatchIdLayoutRoute =
  DashboardAccountsReceivableBatchBatchIdLayoutImport.update({
    id: '/accounts-receivable/batch/$batchId',
    path: '/accounts-receivable/batch/$batchId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardAccountsReceivableBatchNewPageRoute =
  DashboardAccountsReceivableBatchNewPageImport.update({
    id: '/accounts-receivable/batch/new/',
    path: '/accounts-receivable/batch/new/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardAccountsReceivableBatchBatchIdErrorsPageRoute =
  DashboardAccountsReceivableBatchBatchIdErrorsPageImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardAccountsReceivableBatchBatchIdLayoutRoute,
  } as any)

const DashboardAccountsReceivableBatchBatchIdviewPageRoute =
  DashboardAccountsReceivableBatchBatchIdviewPageImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardAccountsReceivableBatchBatchIdLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forget-password': {
      id: '/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginPageImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_public/(home)/': {
      id: '/_public/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublichomePageImport
      parentRoute: typeof PublicLayoutImport
    }
    '/dashboard/(home)/': {
      id: '/dashboard/(home)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardhomePageImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/accounts-payable/': {
      id: '/dashboard/accounts-payable/'
      path: '/accounts-payable'
      fullPath: '/dashboard/accounts-payable'
      preLoaderRoute: typeof DashboardAccountsPayablePageImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/accounts-receivable/': {
      id: '/dashboard/accounts-receivable/'
      path: '/accounts-receivable'
      fullPath: '/dashboard/accounts-receivable'
      preLoaderRoute: typeof DashboardAccountsReceivablePageImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/cash-management/': {
      id: '/dashboard/cash-management/'
      path: '/cash-management'
      fullPath: '/dashboard/cash-management'
      preLoaderRoute: typeof DashboardCashManagementPageImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsPageImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/accounts-receivable/batch/$batchId': {
      id: '/dashboard/accounts-receivable/batch/$batchId'
      path: '/accounts-receivable/batch/$batchId'
      fullPath: '/dashboard/accounts-receivable/batch/$batchId'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/accounts-receivable/batch/': {
      id: '/dashboard/accounts-receivable/batch/'
      path: '/accounts-receivable/batch'
      fullPath: '/dashboard/accounts-receivable/batch'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchPageImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/accounts-receivable/batch/new/': {
      id: '/dashboard/accounts-receivable/batch/new/'
      path: '/accounts-receivable/batch/new'
      fullPath: '/dashboard/accounts-receivable/batch/new'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchNewPageImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/accounts-receivable/batch/$batchId/(view)/': {
      id: '/dashboard/accounts-receivable/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/accounts-receivable/batch/$batchId/'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchBatchIdviewPageImport
      parentRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutImport
    }
    '/dashboard/accounts-receivable/batch/$batchId/errors/': {
      id: '/dashboard/accounts-receivable/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/accounts-receivable/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchBatchIdErrorsPageImport
      parentRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginPageRoute: typeof AuthLoginPageRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginPageRoute: AuthLoginPageRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublichomePageRoute: typeof PublichomePageRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublichomePageRoute: PublichomePageRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren {
  DashboardAccountsReceivableBatchBatchIdviewPageRoute: typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  DashboardAccountsReceivableBatchBatchIdErrorsPageRoute: typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
}

const DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren: DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren =
  {
    DashboardAccountsReceivableBatchBatchIdviewPageRoute:
      DashboardAccountsReceivableBatchBatchIdviewPageRoute,
    DashboardAccountsReceivableBatchBatchIdErrorsPageRoute:
      DashboardAccountsReceivableBatchBatchIdErrorsPageRoute,
  }

const DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren =
  DashboardAccountsReceivableBatchBatchIdLayoutRoute._addFileChildren(
    DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardhomePageRoute: typeof DashboardhomePageRoute
  DashboardAccountsPayablePageRoute: typeof DashboardAccountsPayablePageRoute
  DashboardAccountsReceivablePageRoute: typeof DashboardAccountsReceivablePageRoute
  DashboardCashManagementPageRoute: typeof DashboardCashManagementPageRoute
  DashboardSettingsPageRoute: typeof DashboardSettingsPageRoute
  DashboardAccountsReceivableBatchBatchIdLayoutRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren
  DashboardAccountsReceivableBatchPageRoute: typeof DashboardAccountsReceivableBatchPageRoute
  DashboardAccountsReceivableBatchNewPageRoute: typeof DashboardAccountsReceivableBatchNewPageRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardhomePageRoute: DashboardhomePageRoute,
  DashboardAccountsPayablePageRoute: DashboardAccountsPayablePageRoute,
  DashboardAccountsReceivablePageRoute: DashboardAccountsReceivablePageRoute,
  DashboardCashManagementPageRoute: DashboardCashManagementPageRoute,
  DashboardSettingsPageRoute: DashboardSettingsPageRoute,
  DashboardAccountsReceivableBatchBatchIdLayoutRoute:
    DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren,
  DashboardAccountsReceivableBatchPageRoute:
    DashboardAccountsReceivableBatchPageRoute,
  DashboardAccountsReceivableBatchNewPageRoute:
    DashboardAccountsReceivableBatchNewPageRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PublicLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginPageRoute
  '/': typeof PublichomePageRoute
  '/dashboard/': typeof DashboardhomePageRoute
  '/dashboard/accounts-payable': typeof DashboardAccountsPayablePageRoute
  '/dashboard/accounts-receivable': typeof DashboardAccountsReceivablePageRoute
  '/dashboard/cash-management': typeof DashboardCashManagementPageRoute
  '/dashboard/settings': typeof DashboardSettingsPageRoute
  '/dashboard/accounts-receivable/batch/$batchId': typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren
  '/dashboard/accounts-receivable/batch': typeof DashboardAccountsReceivableBatchPageRoute
  '/dashboard/accounts-receivable/batch/new': typeof DashboardAccountsReceivableBatchNewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/': typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/errors': typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
}

export interface FileRoutesByTo {
  '': typeof AuthLayoutRouteWithChildren
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginPageRoute
  '/': typeof PublichomePageRoute
  '/dashboard': typeof DashboardhomePageRoute
  '/dashboard/accounts-payable': typeof DashboardAccountsPayablePageRoute
  '/dashboard/accounts-receivable': typeof DashboardAccountsReceivablePageRoute
  '/dashboard/cash-management': typeof DashboardCashManagementPageRoute
  '/dashboard/settings': typeof DashboardSettingsPageRoute
  '/dashboard/accounts-receivable/batch': typeof DashboardAccountsReceivableBatchPageRoute
  '/dashboard/accounts-receivable/batch/new': typeof DashboardAccountsReceivableBatchNewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId': typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/errors': typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/_auth/forget-password': typeof AuthForgetPasswordRoute
  '/_auth/login/': typeof AuthLoginPageRoute
  '/_public/(home)/': typeof PublichomePageRoute
  '/dashboard/(home)/': typeof DashboardhomePageRoute
  '/dashboard/accounts-payable/': typeof DashboardAccountsPayablePageRoute
  '/dashboard/accounts-receivable/': typeof DashboardAccountsReceivablePageRoute
  '/dashboard/cash-management/': typeof DashboardCashManagementPageRoute
  '/dashboard/settings/': typeof DashboardSettingsPageRoute
  '/dashboard/accounts-receivable/batch/$batchId': typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren
  '/dashboard/accounts-receivable/batch/': typeof DashboardAccountsReceivableBatchPageRoute
  '/dashboard/accounts-receivable/batch/new/': typeof DashboardAccountsReceivableBatchNewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/(view)/': typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/errors/': typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/forget-password'
    | '/login'
    | '/'
    | '/dashboard/'
    | '/dashboard/accounts-payable'
    | '/dashboard/accounts-receivable'
    | '/dashboard/cash-management'
    | '/dashboard/settings'
    | '/dashboard/accounts-receivable/batch/$batchId'
    | '/dashboard/accounts-receivable/batch'
    | '/dashboard/accounts-receivable/batch/new'
    | '/dashboard/accounts-receivable/batch/$batchId/'
    | '/dashboard/accounts-receivable/batch/$batchId/errors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/forget-password'
    | '/login'
    | '/'
    | '/dashboard'
    | '/dashboard/accounts-payable'
    | '/dashboard/accounts-receivable'
    | '/dashboard/cash-management'
    | '/dashboard/settings'
    | '/dashboard/accounts-receivable/batch'
    | '/dashboard/accounts-receivable/batch/new'
    | '/dashboard/accounts-receivable/batch/$batchId'
    | '/dashboard/accounts-receivable/batch/$batchId/errors'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/dashboard'
    | '/_auth/forget-password'
    | '/_auth/login/'
    | '/_public/(home)/'
    | '/dashboard/(home)/'
    | '/dashboard/accounts-payable/'
    | '/dashboard/accounts-receivable/'
    | '/dashboard/cash-management/'
    | '/dashboard/settings/'
    | '/dashboard/accounts-receivable/batch/$batchId'
    | '/dashboard/accounts-receivable/batch/'
    | '/dashboard/accounts-receivable/batch/new/'
    | '/dashboard/accounts-receivable/batch/$batchId/(view)/'
    | '/dashboard/accounts-receivable/batch/$batchId/errors/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_public",
        "/dashboard"
      ]
    },
    "/_auth": {
      "filePath": "_auth/layout.tsx",
      "children": [
        "/_auth/forget-password",
        "/_auth/login/"
      ]
    },
    "/_public": {
      "filePath": "_public/layout.tsx",
      "children": [
        "/_public/(home)/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/layout.tsx",
      "children": [
        "/dashboard/(home)/",
        "/dashboard/accounts-payable/",
        "/dashboard/accounts-receivable/",
        "/dashboard/cash-management/",
        "/dashboard/settings/",
        "/dashboard/accounts-receivable/batch/$batchId",
        "/dashboard/accounts-receivable/batch/",
        "/dashboard/accounts-receivable/batch/new/"
      ]
    },
    "/_auth/forget-password": {
      "filePath": "_auth/forget-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/login/": {
      "filePath": "_auth/login/page.tsx",
      "parent": "/_auth"
    },
    "/_public/(home)/": {
      "filePath": "_public/(home)/page.tsx",
      "parent": "/_public"
    },
    "/dashboard/(home)/": {
      "filePath": "dashboard/(home)/page.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/accounts-payable/": {
      "filePath": "dashboard/accounts-payable/page.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/accounts-receivable/": {
      "filePath": "dashboard/accounts-receivable/page.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/cash-management/": {
      "filePath": "dashboard/cash-management/page.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings/": {
      "filePath": "dashboard/settings/page.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/accounts-receivable/batch/$batchId": {
      "filePath": "dashboard/accounts-receivable/batch/$batchId/layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/accounts-receivable/batch/$batchId/(view)/",
        "/dashboard/accounts-receivable/batch/$batchId/errors/"
      ]
    },
    "/dashboard/accounts-receivable/batch/": {
      "filePath": "dashboard/accounts-receivable/batch/page.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/accounts-receivable/batch/new/": {
      "filePath": "dashboard/accounts-receivable/batch/new/page.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/accounts-receivable/batch/$batchId/(view)/": {
      "filePath": "dashboard/accounts-receivable/batch/$batchId/(view)/page.tsx",
      "parent": "/dashboard/accounts-receivable/batch/$batchId"
    },
    "/dashboard/accounts-receivable/batch/$batchId/errors/": {
      "filePath": "dashboard/accounts-receivable/batch/$batchId/errors/page.tsx",
      "parent": "/dashboard/accounts-receivable/batch/$batchId"
    }
  }
}
ROUTE_MANIFEST_END */
