/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as AuthForgetPasswordRouteImport } from './routes/_auth/forget-password'
import { Route as DashboardVendorPageRouteImport } from './routes/dashboard/vendor/page'
import { Route as DashboardSettingsPageRouteImport } from './routes/dashboard/settings/page'
import { Route as DashboardLedgerPageRouteImport } from './routes/dashboard/ledger/page'
import { Route as DashboardCashOutPageRouteImport } from './routes/dashboard/cash-out/page'
import { Route as DashboardCashManagementPageRouteImport } from './routes/dashboard/cash-management/page'
import { Route as DashboardCashInPageRouteImport } from './routes/dashboard/cash-in/page'
import { Route as DashboardAccountsReceivablePageRouteImport } from './routes/dashboard/accounts-receivable/page'
import { Route as DashboardAccountsPayablePageRouteImport } from './routes/dashboard/accounts-payable/page'
import { Route as DashboardhomePageRouteImport } from './routes/dashboard/(home)/page'
import { Route as PublichomePageRouteImport } from './routes/_public/(home)/page'
import { Route as AuthLoginPageRouteImport } from './routes/_auth/login/page'
import { Route as DashboardVendorBatchLayoutRouteImport } from './routes/dashboard/vendor/batch/layout'
import { Route as DashboardLedgerBatchLayoutRouteImport } from './routes/dashboard/ledger/batch/layout'
import { Route as DashboardCashOutBatchLayoutRouteImport } from './routes/dashboard/cash-out/batch/layout'
import { Route as DashboardCashManagementBatchLayoutRouteImport } from './routes/dashboard/cash-management/batch/layout'
import { Route as DashboardCashInBatchLayoutRouteImport } from './routes/dashboard/cash-in/batch/layout'
import { Route as DashboardAccountsReceivableBatchLayoutRouteImport } from './routes/dashboard/accounts-receivable/batch/layout'
import { Route as DashboardAccountsPayableBatchLayoutRouteImport } from './routes/dashboard/accounts-payable/batch/layout'
import { Route as DashboardLedgerBatchPageRouteImport } from './routes/dashboard/ledger/batch/page'
import { Route as DashboardCashOutBatchPageRouteImport } from './routes/dashboard/cash-out/batch/page'
import { Route as DashboardCashManagementBatchPageRouteImport } from './routes/dashboard/cash-management/batch/page'
import { Route as DashboardCashInBatchPageRouteImport } from './routes/dashboard/cash-in/batch/page'
import { Route as DashboardAccountsReceivableBatchPageRouteImport } from './routes/dashboard/accounts-receivable/batch/page'
import { Route as DashboardAccountsPayableBatchPageRouteImport } from './routes/dashboard/accounts-payable/batch/page'
import { Route as DashboardVendorBatchBatchIdLayoutRouteImport } from './routes/dashboard/vendor/batch/$batchId/layout'
import { Route as DashboardLedgerBatchBatchIdLayoutRouteImport } from './routes/dashboard/ledger/batch/$batchId/layout'
import { Route as DashboardCashOutBatchBatchIdLayoutRouteImport } from './routes/dashboard/cash-out/batch/$batchId/layout'
import { Route as DashboardCashManagementBatchBatchIdLayoutRouteImport } from './routes/dashboard/cash-management/batch/$batchId/layout'
import { Route as DashboardCashInBatchBatchIdLayoutRouteImport } from './routes/dashboard/cash-in/batch/$batchId/layout'
import { Route as DashboardAccountsReceivableBatchBatchIdLayoutRouteImport } from './routes/dashboard/accounts-receivable/batch/$batchId/layout'
import { Route as DashboardAccountsPayableBatchBatchIdLayoutRouteImport } from './routes/dashboard/accounts-payable/batch/$batchId/layout'
import { Route as DashboardVendorBatchNewPageRouteImport } from './routes/dashboard/vendor/batch/new/page'
import { Route as DashboardLedgerBatchNewPageRouteImport } from './routes/dashboard/ledger/batch/new/page'
import { Route as DashboardCashOutBatchNewPageRouteImport } from './routes/dashboard/cash-out/batch/new/page'
import { Route as DashboardCashManagementBatchNewPageRouteImport } from './routes/dashboard/cash-management/batch/new/page'
import { Route as DashboardCashInBatchNewPageRouteImport } from './routes/dashboard/cash-in/batch/new/page'
import { Route as DashboardAccountsReceivableBatchNewPageRouteImport } from './routes/dashboard/accounts-receivable/batch/new/page'
import { Route as DashboardAccountsPayableBatchNewPageRouteImport } from './routes/dashboard/accounts-payable/batch/new/page'
import { Route as DashboardVendorBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/vendor/batch/$batchId/errors/page'
import { Route as DashboardVendorBatchBatchIdviewPageRouteImport } from './routes/dashboard/vendor/batch/$batchId/(view)/page'
import { Route as DashboardLedgerBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/ledger/batch/$batchId/errors/page'
import { Route as DashboardLedgerBatchBatchIdviewPageRouteImport } from './routes/dashboard/ledger/batch/$batchId/(view)/page'
import { Route as DashboardCashOutBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/cash-out/batch/$batchId/errors/page'
import { Route as DashboardCashOutBatchBatchIdviewPageRouteImport } from './routes/dashboard/cash-out/batch/$batchId/(view)/page'
import { Route as DashboardCashManagementBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/cash-management/batch/$batchId/errors/page'
import { Route as DashboardCashManagementBatchBatchIdviewPageRouteImport } from './routes/dashboard/cash-management/batch/$batchId/(view)/page'
import { Route as DashboardCashInBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/cash-in/batch/$batchId/errors/page'
import { Route as DashboardCashInBatchBatchIdviewPageRouteImport } from './routes/dashboard/cash-in/batch/$batchId/(view)/page'
import { Route as DashboardAccountsReceivableBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/accounts-receivable/batch/$batchId/errors/page'
import { Route as DashboardAccountsReceivableBatchBatchIdviewPageRouteImport } from './routes/dashboard/accounts-receivable/batch/$batchId/(view)/page'
import { Route as DashboardAccountsPayableBatchBatchIdErrorsPageRouteImport } from './routes/dashboard/accounts-payable/batch/$batchId/errors/page'
import { Route as DashboardAccountsPayableBatchBatchIdviewPageRouteImport } from './routes/dashboard/accounts-payable/batch/$batchId/(view)/page'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardVendorPageRoute = DashboardVendorPageRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardSettingsPageRoute = DashboardSettingsPageRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLedgerPageRoute = DashboardLedgerPageRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardCashOutPageRoute = DashboardCashOutPageRouteImport.update({
  id: '/cash-out/',
  path: '/cash-out/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardCashManagementPageRoute =
  DashboardCashManagementPageRouteImport.update({
    id: '/cash-management/',
    path: '/cash-management/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardCashInPageRoute = DashboardCashInPageRouteImport.update({
  id: '/cash-in/',
  path: '/cash-in/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardAccountsReceivablePageRoute =
  DashboardAccountsReceivablePageRouteImport.update({
    id: '/accounts-receivable/',
    path: '/accounts-receivable/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAccountsPayablePageRoute =
  DashboardAccountsPayablePageRouteImport.update({
    id: '/accounts-payable/',
    path: '/accounts-payable/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardhomePageRoute = DashboardhomePageRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const PublichomePageRoute = PublichomePageRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthLoginPageRoute = AuthLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardVendorBatchLayoutRoute =
  DashboardVendorBatchLayoutRouteImport.update({
    id: '/vendor/batch',
    path: '/vendor/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLedgerBatchLayoutRoute =
  DashboardLedgerBatchLayoutRouteImport.update({
    id: '/ledger/batch',
    path: '/ledger/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardCashOutBatchLayoutRoute =
  DashboardCashOutBatchLayoutRouteImport.update({
    id: '/cash-out/batch',
    path: '/cash-out/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardCashManagementBatchLayoutRoute =
  DashboardCashManagementBatchLayoutRouteImport.update({
    id: '/cash-management/batch',
    path: '/cash-management/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardCashInBatchLayoutRoute =
  DashboardCashInBatchLayoutRouteImport.update({
    id: '/cash-in/batch',
    path: '/cash-in/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchLayoutRoute =
  DashboardAccountsReceivableBatchLayoutRouteImport.update({
    id: '/accounts-receivable/batch',
    path: '/accounts-receivable/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchLayoutRoute =
  DashboardAccountsPayableBatchLayoutRouteImport.update({
    id: '/accounts-payable/batch',
    path: '/accounts-payable/batch',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLedgerBatchPageRoute =
  DashboardLedgerBatchPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLedgerBatchLayoutRoute,
  } as any)
const DashboardCashOutBatchPageRoute =
  DashboardCashOutBatchPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCashOutBatchLayoutRoute,
  } as any)
const DashboardCashManagementBatchPageRoute =
  DashboardCashManagementBatchPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCashManagementBatchLayoutRoute,
  } as any)
const DashboardCashInBatchPageRoute =
  DashboardCashInBatchPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCashInBatchLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchPageRoute =
  DashboardAccountsReceivableBatchPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountsReceivableBatchLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchPageRoute =
  DashboardAccountsPayableBatchPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountsPayableBatchLayoutRoute,
  } as any)
const DashboardVendorBatchBatchIdLayoutRoute =
  DashboardVendorBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardVendorBatchLayoutRoute,
  } as any)
const DashboardLedgerBatchBatchIdLayoutRoute =
  DashboardLedgerBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardLedgerBatchLayoutRoute,
  } as any)
const DashboardCashOutBatchBatchIdLayoutRoute =
  DashboardCashOutBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardCashOutBatchLayoutRoute,
  } as any)
const DashboardCashManagementBatchBatchIdLayoutRoute =
  DashboardCashManagementBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardCashManagementBatchLayoutRoute,
  } as any)
const DashboardCashInBatchBatchIdLayoutRoute =
  DashboardCashInBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardCashInBatchLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchBatchIdLayoutRoute =
  DashboardAccountsReceivableBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardAccountsReceivableBatchLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchBatchIdLayoutRoute =
  DashboardAccountsPayableBatchBatchIdLayoutRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => DashboardAccountsPayableBatchLayoutRoute,
  } as any)
const DashboardVendorBatchNewPageRoute =
  DashboardVendorBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardVendorBatchLayoutRoute,
  } as any)
const DashboardLedgerBatchNewPageRoute =
  DashboardLedgerBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardLedgerBatchLayoutRoute,
  } as any)
const DashboardCashOutBatchNewPageRoute =
  DashboardCashOutBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardCashOutBatchLayoutRoute,
  } as any)
const DashboardCashManagementBatchNewPageRoute =
  DashboardCashManagementBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardCashManagementBatchLayoutRoute,
  } as any)
const DashboardCashInBatchNewPageRoute =
  DashboardCashInBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardCashInBatchLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchNewPageRoute =
  DashboardAccountsReceivableBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardAccountsReceivableBatchLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchNewPageRoute =
  DashboardAccountsPayableBatchNewPageRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardAccountsPayableBatchLayoutRoute,
  } as any)
const DashboardVendorBatchBatchIdErrorsPageRoute =
  DashboardVendorBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardVendorBatchBatchIdLayoutRoute,
  } as any)
const DashboardVendorBatchBatchIdviewPageRoute =
  DashboardVendorBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardVendorBatchBatchIdLayoutRoute,
  } as any)
const DashboardLedgerBatchBatchIdErrorsPageRoute =
  DashboardLedgerBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardLedgerBatchBatchIdLayoutRoute,
  } as any)
const DashboardLedgerBatchBatchIdviewPageRoute =
  DashboardLedgerBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardLedgerBatchBatchIdLayoutRoute,
  } as any)
const DashboardCashOutBatchBatchIdErrorsPageRoute =
  DashboardCashOutBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardCashOutBatchBatchIdLayoutRoute,
  } as any)
const DashboardCashOutBatchBatchIdviewPageRoute =
  DashboardCashOutBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardCashOutBatchBatchIdLayoutRoute,
  } as any)
const DashboardCashManagementBatchBatchIdErrorsPageRoute =
  DashboardCashManagementBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardCashManagementBatchBatchIdLayoutRoute,
  } as any)
const DashboardCashManagementBatchBatchIdviewPageRoute =
  DashboardCashManagementBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardCashManagementBatchBatchIdLayoutRoute,
  } as any)
const DashboardCashInBatchBatchIdErrorsPageRoute =
  DashboardCashInBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardCashInBatchBatchIdLayoutRoute,
  } as any)
const DashboardCashInBatchBatchIdviewPageRoute =
  DashboardCashInBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardCashInBatchBatchIdLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchBatchIdErrorsPageRoute =
  DashboardAccountsReceivableBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardAccountsReceivableBatchBatchIdLayoutRoute,
  } as any)
const DashboardAccountsReceivableBatchBatchIdviewPageRoute =
  DashboardAccountsReceivableBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardAccountsReceivableBatchBatchIdLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchBatchIdErrorsPageRoute =
  DashboardAccountsPayableBatchBatchIdErrorsPageRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => DashboardAccountsPayableBatchBatchIdLayoutRoute,
  } as any)
const DashboardAccountsPayableBatchBatchIdviewPageRoute =
  DashboardAccountsPayableBatchBatchIdviewPageRouteImport.update({
    id: '/(view)/',
    path: '/',
    getParentRoute: () => DashboardAccountsPayableBatchBatchIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/forget-password': typeof AuthForgetPasswordRoute
  '/dashboard/accounts-payable/batch': typeof DashboardAccountsPayableBatchLayoutRouteWithChildren
  '/dashboard/accounts-receivable/batch': typeof DashboardAccountsReceivableBatchLayoutRouteWithChildren
  '/dashboard/cash-in/batch': typeof DashboardCashInBatchLayoutRouteWithChildren
  '/dashboard/cash-management/batch': typeof DashboardCashManagementBatchLayoutRouteWithChildren
  '/dashboard/cash-out/batch': typeof DashboardCashOutBatchLayoutRouteWithChildren
  '/dashboard/ledger/batch': typeof DashboardLedgerBatchLayoutRouteWithChildren
  '/dashboard/vendor/batch': typeof DashboardVendorBatchLayoutRouteWithChildren
  '/login': typeof AuthLoginPageRoute
  '/': typeof PublichomePageRoute
  '/dashboard/': typeof DashboardhomePageRoute
  '/dashboard/accounts-payable': typeof DashboardAccountsPayablePageRoute
  '/dashboard/accounts-receivable': typeof DashboardAccountsReceivablePageRoute
  '/dashboard/cash-in': typeof DashboardCashInPageRoute
  '/dashboard/cash-management': typeof DashboardCashManagementPageRoute
  '/dashboard/cash-out': typeof DashboardCashOutPageRoute
  '/dashboard/ledger': typeof DashboardLedgerPageRoute
  '/dashboard/settings': typeof DashboardSettingsPageRoute
  '/dashboard/vendor': typeof DashboardVendorPageRoute
  '/dashboard/accounts-payable/batch/$batchId': typeof DashboardAccountsPayableBatchBatchIdLayoutRouteWithChildren
  '/dashboard/accounts-receivable/batch/$batchId': typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren
  '/dashboard/cash-in/batch/$batchId': typeof DashboardCashInBatchBatchIdLayoutRouteWithChildren
  '/dashboard/cash-management/batch/$batchId': typeof DashboardCashManagementBatchBatchIdLayoutRouteWithChildren
  '/dashboard/cash-out/batch/$batchId': typeof DashboardCashOutBatchBatchIdLayoutRouteWithChildren
  '/dashboard/ledger/batch/$batchId': typeof DashboardLedgerBatchBatchIdLayoutRouteWithChildren
  '/dashboard/vendor/batch/$batchId': typeof DashboardVendorBatchBatchIdLayoutRouteWithChildren
  '/dashboard/accounts-payable/batch/': typeof DashboardAccountsPayableBatchPageRoute
  '/dashboard/accounts-receivable/batch/': typeof DashboardAccountsReceivableBatchPageRoute
  '/dashboard/cash-in/batch/': typeof DashboardCashInBatchPageRoute
  '/dashboard/cash-management/batch/': typeof DashboardCashManagementBatchPageRoute
  '/dashboard/cash-out/batch/': typeof DashboardCashOutBatchPageRoute
  '/dashboard/ledger/batch/': typeof DashboardLedgerBatchPageRoute
  '/dashboard/accounts-payable/batch/new': typeof DashboardAccountsPayableBatchNewPageRoute
  '/dashboard/accounts-receivable/batch/new': typeof DashboardAccountsReceivableBatchNewPageRoute
  '/dashboard/cash-in/batch/new': typeof DashboardCashInBatchNewPageRoute
  '/dashboard/cash-management/batch/new': typeof DashboardCashManagementBatchNewPageRoute
  '/dashboard/cash-out/batch/new': typeof DashboardCashOutBatchNewPageRoute
  '/dashboard/ledger/batch/new': typeof DashboardLedgerBatchNewPageRoute
  '/dashboard/vendor/batch/new': typeof DashboardVendorBatchNewPageRoute
  '/dashboard/accounts-payable/batch/$batchId/': typeof DashboardAccountsPayableBatchBatchIdviewPageRoute
  '/dashboard/accounts-payable/batch/$batchId/errors': typeof DashboardAccountsPayableBatchBatchIdErrorsPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/': typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/errors': typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
  '/dashboard/cash-in/batch/$batchId/': typeof DashboardCashInBatchBatchIdviewPageRoute
  '/dashboard/cash-in/batch/$batchId/errors': typeof DashboardCashInBatchBatchIdErrorsPageRoute
  '/dashboard/cash-management/batch/$batchId/': typeof DashboardCashManagementBatchBatchIdviewPageRoute
  '/dashboard/cash-management/batch/$batchId/errors': typeof DashboardCashManagementBatchBatchIdErrorsPageRoute
  '/dashboard/cash-out/batch/$batchId/': typeof DashboardCashOutBatchBatchIdviewPageRoute
  '/dashboard/cash-out/batch/$batchId/errors': typeof DashboardCashOutBatchBatchIdErrorsPageRoute
  '/dashboard/ledger/batch/$batchId/': typeof DashboardLedgerBatchBatchIdviewPageRoute
  '/dashboard/ledger/batch/$batchId/errors': typeof DashboardLedgerBatchBatchIdErrorsPageRoute
  '/dashboard/vendor/batch/$batchId/': typeof DashboardVendorBatchBatchIdviewPageRoute
  '/dashboard/vendor/batch/$batchId/errors': typeof DashboardVendorBatchBatchIdErrorsPageRoute
}
export interface FileRoutesByTo {
  '/forget-password': typeof AuthForgetPasswordRoute
  '/dashboard/vendor/batch': typeof DashboardVendorBatchLayoutRouteWithChildren
  '/login': typeof AuthLoginPageRoute
  '/': typeof PublichomePageRoute
  '/dashboard': typeof DashboardhomePageRoute
  '/dashboard/accounts-payable': typeof DashboardAccountsPayablePageRoute
  '/dashboard/accounts-receivable': typeof DashboardAccountsReceivablePageRoute
  '/dashboard/cash-in': typeof DashboardCashInPageRoute
  '/dashboard/cash-management': typeof DashboardCashManagementPageRoute
  '/dashboard/cash-out': typeof DashboardCashOutPageRoute
  '/dashboard/ledger': typeof DashboardLedgerPageRoute
  '/dashboard/settings': typeof DashboardSettingsPageRoute
  '/dashboard/vendor': typeof DashboardVendorPageRoute
  '/dashboard/accounts-payable/batch': typeof DashboardAccountsPayableBatchPageRoute
  '/dashboard/accounts-receivable/batch': typeof DashboardAccountsReceivableBatchPageRoute
  '/dashboard/cash-in/batch': typeof DashboardCashInBatchPageRoute
  '/dashboard/cash-management/batch': typeof DashboardCashManagementBatchPageRoute
  '/dashboard/cash-out/batch': typeof DashboardCashOutBatchPageRoute
  '/dashboard/ledger/batch': typeof DashboardLedgerBatchPageRoute
  '/dashboard/accounts-payable/batch/new': typeof DashboardAccountsPayableBatchNewPageRoute
  '/dashboard/accounts-receivable/batch/new': typeof DashboardAccountsReceivableBatchNewPageRoute
  '/dashboard/cash-in/batch/new': typeof DashboardCashInBatchNewPageRoute
  '/dashboard/cash-management/batch/new': typeof DashboardCashManagementBatchNewPageRoute
  '/dashboard/cash-out/batch/new': typeof DashboardCashOutBatchNewPageRoute
  '/dashboard/ledger/batch/new': typeof DashboardLedgerBatchNewPageRoute
  '/dashboard/vendor/batch/new': typeof DashboardVendorBatchNewPageRoute
  '/dashboard/accounts-payable/batch/$batchId': typeof DashboardAccountsPayableBatchBatchIdviewPageRoute
  '/dashboard/accounts-payable/batch/$batchId/errors': typeof DashboardAccountsPayableBatchBatchIdErrorsPageRoute
  '/dashboard/accounts-receivable/batch/$batchId': typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/errors': typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
  '/dashboard/cash-in/batch/$batchId': typeof DashboardCashInBatchBatchIdviewPageRoute
  '/dashboard/cash-in/batch/$batchId/errors': typeof DashboardCashInBatchBatchIdErrorsPageRoute
  '/dashboard/cash-management/batch/$batchId': typeof DashboardCashManagementBatchBatchIdviewPageRoute
  '/dashboard/cash-management/batch/$batchId/errors': typeof DashboardCashManagementBatchBatchIdErrorsPageRoute
  '/dashboard/cash-out/batch/$batchId': typeof DashboardCashOutBatchBatchIdviewPageRoute
  '/dashboard/cash-out/batch/$batchId/errors': typeof DashboardCashOutBatchBatchIdErrorsPageRoute
  '/dashboard/ledger/batch/$batchId': typeof DashboardLedgerBatchBatchIdviewPageRoute
  '/dashboard/ledger/batch/$batchId/errors': typeof DashboardLedgerBatchBatchIdErrorsPageRoute
  '/dashboard/vendor/batch/$batchId': typeof DashboardVendorBatchBatchIdviewPageRoute
  '/dashboard/vendor/batch/$batchId/errors': typeof DashboardVendorBatchBatchIdErrorsPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/_auth/forget-password': typeof AuthForgetPasswordRoute
  '/dashboard/accounts-payable/batch': typeof DashboardAccountsPayableBatchLayoutRouteWithChildren
  '/dashboard/accounts-receivable/batch': typeof DashboardAccountsReceivableBatchLayoutRouteWithChildren
  '/dashboard/cash-in/batch': typeof DashboardCashInBatchLayoutRouteWithChildren
  '/dashboard/cash-management/batch': typeof DashboardCashManagementBatchLayoutRouteWithChildren
  '/dashboard/cash-out/batch': typeof DashboardCashOutBatchLayoutRouteWithChildren
  '/dashboard/ledger/batch': typeof DashboardLedgerBatchLayoutRouteWithChildren
  '/dashboard/vendor/batch': typeof DashboardVendorBatchLayoutRouteWithChildren
  '/_auth/login/': typeof AuthLoginPageRoute
  '/_public/(home)/': typeof PublichomePageRoute
  '/dashboard/(home)/': typeof DashboardhomePageRoute
  '/dashboard/accounts-payable/': typeof DashboardAccountsPayablePageRoute
  '/dashboard/accounts-receivable/': typeof DashboardAccountsReceivablePageRoute
  '/dashboard/cash-in/': typeof DashboardCashInPageRoute
  '/dashboard/cash-management/': typeof DashboardCashManagementPageRoute
  '/dashboard/cash-out/': typeof DashboardCashOutPageRoute
  '/dashboard/ledger/': typeof DashboardLedgerPageRoute
  '/dashboard/settings/': typeof DashboardSettingsPageRoute
  '/dashboard/vendor/': typeof DashboardVendorPageRoute
  '/dashboard/accounts-payable/batch/$batchId': typeof DashboardAccountsPayableBatchBatchIdLayoutRouteWithChildren
  '/dashboard/accounts-receivable/batch/$batchId': typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren
  '/dashboard/cash-in/batch/$batchId': typeof DashboardCashInBatchBatchIdLayoutRouteWithChildren
  '/dashboard/cash-management/batch/$batchId': typeof DashboardCashManagementBatchBatchIdLayoutRouteWithChildren
  '/dashboard/cash-out/batch/$batchId': typeof DashboardCashOutBatchBatchIdLayoutRouteWithChildren
  '/dashboard/ledger/batch/$batchId': typeof DashboardLedgerBatchBatchIdLayoutRouteWithChildren
  '/dashboard/vendor/batch/$batchId': typeof DashboardVendorBatchBatchIdLayoutRouteWithChildren
  '/dashboard/accounts-payable/batch/': typeof DashboardAccountsPayableBatchPageRoute
  '/dashboard/accounts-receivable/batch/': typeof DashboardAccountsReceivableBatchPageRoute
  '/dashboard/cash-in/batch/': typeof DashboardCashInBatchPageRoute
  '/dashboard/cash-management/batch/': typeof DashboardCashManagementBatchPageRoute
  '/dashboard/cash-out/batch/': typeof DashboardCashOutBatchPageRoute
  '/dashboard/ledger/batch/': typeof DashboardLedgerBatchPageRoute
  '/dashboard/accounts-payable/batch/new/': typeof DashboardAccountsPayableBatchNewPageRoute
  '/dashboard/accounts-receivable/batch/new/': typeof DashboardAccountsReceivableBatchNewPageRoute
  '/dashboard/cash-in/batch/new/': typeof DashboardCashInBatchNewPageRoute
  '/dashboard/cash-management/batch/new/': typeof DashboardCashManagementBatchNewPageRoute
  '/dashboard/cash-out/batch/new/': typeof DashboardCashOutBatchNewPageRoute
  '/dashboard/ledger/batch/new/': typeof DashboardLedgerBatchNewPageRoute
  '/dashboard/vendor/batch/new/': typeof DashboardVendorBatchNewPageRoute
  '/dashboard/accounts-payable/batch/$batchId/(view)/': typeof DashboardAccountsPayableBatchBatchIdviewPageRoute
  '/dashboard/accounts-payable/batch/$batchId/errors/': typeof DashboardAccountsPayableBatchBatchIdErrorsPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/(view)/': typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  '/dashboard/accounts-receivable/batch/$batchId/errors/': typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
  '/dashboard/cash-in/batch/$batchId/(view)/': typeof DashboardCashInBatchBatchIdviewPageRoute
  '/dashboard/cash-in/batch/$batchId/errors/': typeof DashboardCashInBatchBatchIdErrorsPageRoute
  '/dashboard/cash-management/batch/$batchId/(view)/': typeof DashboardCashManagementBatchBatchIdviewPageRoute
  '/dashboard/cash-management/batch/$batchId/errors/': typeof DashboardCashManagementBatchBatchIdErrorsPageRoute
  '/dashboard/cash-out/batch/$batchId/(view)/': typeof DashboardCashOutBatchBatchIdviewPageRoute
  '/dashboard/cash-out/batch/$batchId/errors/': typeof DashboardCashOutBatchBatchIdErrorsPageRoute
  '/dashboard/ledger/batch/$batchId/(view)/': typeof DashboardLedgerBatchBatchIdviewPageRoute
  '/dashboard/ledger/batch/$batchId/errors/': typeof DashboardLedgerBatchBatchIdErrorsPageRoute
  '/dashboard/vendor/batch/$batchId/(view)/': typeof DashboardVendorBatchBatchIdviewPageRoute
  '/dashboard/vendor/batch/$batchId/errors/': typeof DashboardVendorBatchBatchIdErrorsPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/forget-password'
    | '/dashboard/accounts-payable/batch'
    | '/dashboard/accounts-receivable/batch'
    | '/dashboard/cash-in/batch'
    | '/dashboard/cash-management/batch'
    | '/dashboard/cash-out/batch'
    | '/dashboard/ledger/batch'
    | '/dashboard/vendor/batch'
    | '/login'
    | '/'
    | '/dashboard/'
    | '/dashboard/accounts-payable'
    | '/dashboard/accounts-receivable'
    | '/dashboard/cash-in'
    | '/dashboard/cash-management'
    | '/dashboard/cash-out'
    | '/dashboard/ledger'
    | '/dashboard/settings'
    | '/dashboard/vendor'
    | '/dashboard/accounts-payable/batch/$batchId'
    | '/dashboard/accounts-receivable/batch/$batchId'
    | '/dashboard/cash-in/batch/$batchId'
    | '/dashboard/cash-management/batch/$batchId'
    | '/dashboard/cash-out/batch/$batchId'
    | '/dashboard/ledger/batch/$batchId'
    | '/dashboard/vendor/batch/$batchId'
    | '/dashboard/accounts-payable/batch/'
    | '/dashboard/accounts-receivable/batch/'
    | '/dashboard/cash-in/batch/'
    | '/dashboard/cash-management/batch/'
    | '/dashboard/cash-out/batch/'
    | '/dashboard/ledger/batch/'
    | '/dashboard/accounts-payable/batch/new'
    | '/dashboard/accounts-receivable/batch/new'
    | '/dashboard/cash-in/batch/new'
    | '/dashboard/cash-management/batch/new'
    | '/dashboard/cash-out/batch/new'
    | '/dashboard/ledger/batch/new'
    | '/dashboard/vendor/batch/new'
    | '/dashboard/accounts-payable/batch/$batchId/'
    | '/dashboard/accounts-payable/batch/$batchId/errors'
    | '/dashboard/accounts-receivable/batch/$batchId/'
    | '/dashboard/accounts-receivable/batch/$batchId/errors'
    | '/dashboard/cash-in/batch/$batchId/'
    | '/dashboard/cash-in/batch/$batchId/errors'
    | '/dashboard/cash-management/batch/$batchId/'
    | '/dashboard/cash-management/batch/$batchId/errors'
    | '/dashboard/cash-out/batch/$batchId/'
    | '/dashboard/cash-out/batch/$batchId/errors'
    | '/dashboard/ledger/batch/$batchId/'
    | '/dashboard/ledger/batch/$batchId/errors'
    | '/dashboard/vendor/batch/$batchId/'
    | '/dashboard/vendor/batch/$batchId/errors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forget-password'
    | '/dashboard/vendor/batch'
    | '/login'
    | '/'
    | '/dashboard'
    | '/dashboard/accounts-payable'
    | '/dashboard/accounts-receivable'
    | '/dashboard/cash-in'
    | '/dashboard/cash-management'
    | '/dashboard/cash-out'
    | '/dashboard/ledger'
    | '/dashboard/settings'
    | '/dashboard/vendor'
    | '/dashboard/accounts-payable/batch'
    | '/dashboard/accounts-receivable/batch'
    | '/dashboard/cash-in/batch'
    | '/dashboard/cash-management/batch'
    | '/dashboard/cash-out/batch'
    | '/dashboard/ledger/batch'
    | '/dashboard/accounts-payable/batch/new'
    | '/dashboard/accounts-receivable/batch/new'
    | '/dashboard/cash-in/batch/new'
    | '/dashboard/cash-management/batch/new'
    | '/dashboard/cash-out/batch/new'
    | '/dashboard/ledger/batch/new'
    | '/dashboard/vendor/batch/new'
    | '/dashboard/accounts-payable/batch/$batchId'
    | '/dashboard/accounts-payable/batch/$batchId/errors'
    | '/dashboard/accounts-receivable/batch/$batchId'
    | '/dashboard/accounts-receivable/batch/$batchId/errors'
    | '/dashboard/cash-in/batch/$batchId'
    | '/dashboard/cash-in/batch/$batchId/errors'
    | '/dashboard/cash-management/batch/$batchId'
    | '/dashboard/cash-management/batch/$batchId/errors'
    | '/dashboard/cash-out/batch/$batchId'
    | '/dashboard/cash-out/batch/$batchId/errors'
    | '/dashboard/ledger/batch/$batchId'
    | '/dashboard/ledger/batch/$batchId/errors'
    | '/dashboard/vendor/batch/$batchId'
    | '/dashboard/vendor/batch/$batchId/errors'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/dashboard'
    | '/_auth/forget-password'
    | '/dashboard/accounts-payable/batch'
    | '/dashboard/accounts-receivable/batch'
    | '/dashboard/cash-in/batch'
    | '/dashboard/cash-management/batch'
    | '/dashboard/cash-out/batch'
    | '/dashboard/ledger/batch'
    | '/dashboard/vendor/batch'
    | '/_auth/login/'
    | '/_public/(home)/'
    | '/dashboard/(home)/'
    | '/dashboard/accounts-payable/'
    | '/dashboard/accounts-receivable/'
    | '/dashboard/cash-in/'
    | '/dashboard/cash-management/'
    | '/dashboard/cash-out/'
    | '/dashboard/ledger/'
    | '/dashboard/settings/'
    | '/dashboard/vendor/'
    | '/dashboard/accounts-payable/batch/$batchId'
    | '/dashboard/accounts-receivable/batch/$batchId'
    | '/dashboard/cash-in/batch/$batchId'
    | '/dashboard/cash-management/batch/$batchId'
    | '/dashboard/cash-out/batch/$batchId'
    | '/dashboard/ledger/batch/$batchId'
    | '/dashboard/vendor/batch/$batchId'
    | '/dashboard/accounts-payable/batch/'
    | '/dashboard/accounts-receivable/batch/'
    | '/dashboard/cash-in/batch/'
    | '/dashboard/cash-management/batch/'
    | '/dashboard/cash-out/batch/'
    | '/dashboard/ledger/batch/'
    | '/dashboard/accounts-payable/batch/new/'
    | '/dashboard/accounts-receivable/batch/new/'
    | '/dashboard/cash-in/batch/new/'
    | '/dashboard/cash-management/batch/new/'
    | '/dashboard/cash-out/batch/new/'
    | '/dashboard/ledger/batch/new/'
    | '/dashboard/vendor/batch/new/'
    | '/dashboard/accounts-payable/batch/$batchId/(view)/'
    | '/dashboard/accounts-payable/batch/$batchId/errors/'
    | '/dashboard/accounts-receivable/batch/$batchId/(view)/'
    | '/dashboard/accounts-receivable/batch/$batchId/errors/'
    | '/dashboard/cash-in/batch/$batchId/(view)/'
    | '/dashboard/cash-in/batch/$batchId/errors/'
    | '/dashboard/cash-management/batch/$batchId/(view)/'
    | '/dashboard/cash-management/batch/$batchId/errors/'
    | '/dashboard/cash-out/batch/$batchId/(view)/'
    | '/dashboard/cash-out/batch/$batchId/errors/'
    | '/dashboard/ledger/batch/$batchId/(view)/'
    | '/dashboard/ledger/batch/$batchId/errors/'
    | '/dashboard/vendor/batch/$batchId/(view)/'
    | '/dashboard/vendor/batch/$batchId/errors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forget-password': {
      id: '/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/vendor/': {
      id: '/dashboard/vendor/'
      path: '/vendor'
      fullPath: '/dashboard/vendor'
      preLoaderRoute: typeof DashboardVendorPageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsPageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/ledger/': {
      id: '/dashboard/ledger/'
      path: '/ledger'
      fullPath: '/dashboard/ledger'
      preLoaderRoute: typeof DashboardLedgerPageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/cash-out/': {
      id: '/dashboard/cash-out/'
      path: '/cash-out'
      fullPath: '/dashboard/cash-out'
      preLoaderRoute: typeof DashboardCashOutPageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/cash-management/': {
      id: '/dashboard/cash-management/'
      path: '/cash-management'
      fullPath: '/dashboard/cash-management'
      preLoaderRoute: typeof DashboardCashManagementPageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/cash-in/': {
      id: '/dashboard/cash-in/'
      path: '/cash-in'
      fullPath: '/dashboard/cash-in'
      preLoaderRoute: typeof DashboardCashInPageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/accounts-receivable/': {
      id: '/dashboard/accounts-receivable/'
      path: '/accounts-receivable'
      fullPath: '/dashboard/accounts-receivable'
      preLoaderRoute: typeof DashboardAccountsReceivablePageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/accounts-payable/': {
      id: '/dashboard/accounts-payable/'
      path: '/accounts-payable'
      fullPath: '/dashboard/accounts-payable'
      preLoaderRoute: typeof DashboardAccountsPayablePageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/(home)/': {
      id: '/dashboard/(home)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardhomePageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_public/(home)/': {
      id: '/_public/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublichomePageRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/vendor/batch': {
      id: '/dashboard/vendor/batch'
      path: '/vendor/batch'
      fullPath: '/dashboard/vendor/batch'
      preLoaderRoute: typeof DashboardVendorBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/ledger/batch': {
      id: '/dashboard/ledger/batch'
      path: '/ledger/batch'
      fullPath: '/dashboard/ledger/batch'
      preLoaderRoute: typeof DashboardLedgerBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/cash-out/batch': {
      id: '/dashboard/cash-out/batch'
      path: '/cash-out/batch'
      fullPath: '/dashboard/cash-out/batch'
      preLoaderRoute: typeof DashboardCashOutBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/cash-management/batch': {
      id: '/dashboard/cash-management/batch'
      path: '/cash-management/batch'
      fullPath: '/dashboard/cash-management/batch'
      preLoaderRoute: typeof DashboardCashManagementBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/cash-in/batch': {
      id: '/dashboard/cash-in/batch'
      path: '/cash-in/batch'
      fullPath: '/dashboard/cash-in/batch'
      preLoaderRoute: typeof DashboardCashInBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/accounts-receivable/batch': {
      id: '/dashboard/accounts-receivable/batch'
      path: '/accounts-receivable/batch'
      fullPath: '/dashboard/accounts-receivable/batch'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/accounts-payable/batch': {
      id: '/dashboard/accounts-payable/batch'
      path: '/accounts-payable/batch'
      fullPath: '/dashboard/accounts-payable/batch'
      preLoaderRoute: typeof DashboardAccountsPayableBatchLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/ledger/batch/': {
      id: '/dashboard/ledger/batch/'
      path: '/'
      fullPath: '/dashboard/ledger/batch/'
      preLoaderRoute: typeof DashboardLedgerBatchPageRouteImport
      parentRoute: typeof DashboardLedgerBatchLayoutRoute
    }
    '/dashboard/cash-out/batch/': {
      id: '/dashboard/cash-out/batch/'
      path: '/'
      fullPath: '/dashboard/cash-out/batch/'
      preLoaderRoute: typeof DashboardCashOutBatchPageRouteImport
      parentRoute: typeof DashboardCashOutBatchLayoutRoute
    }
    '/dashboard/cash-management/batch/': {
      id: '/dashboard/cash-management/batch/'
      path: '/'
      fullPath: '/dashboard/cash-management/batch/'
      preLoaderRoute: typeof DashboardCashManagementBatchPageRouteImport
      parentRoute: typeof DashboardCashManagementBatchLayoutRoute
    }
    '/dashboard/cash-in/batch/': {
      id: '/dashboard/cash-in/batch/'
      path: '/'
      fullPath: '/dashboard/cash-in/batch/'
      preLoaderRoute: typeof DashboardCashInBatchPageRouteImport
      parentRoute: typeof DashboardCashInBatchLayoutRoute
    }
    '/dashboard/accounts-receivable/batch/': {
      id: '/dashboard/accounts-receivable/batch/'
      path: '/'
      fullPath: '/dashboard/accounts-receivable/batch/'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchPageRouteImport
      parentRoute: typeof DashboardAccountsReceivableBatchLayoutRoute
    }
    '/dashboard/accounts-payable/batch/': {
      id: '/dashboard/accounts-payable/batch/'
      path: '/'
      fullPath: '/dashboard/accounts-payable/batch/'
      preLoaderRoute: typeof DashboardAccountsPayableBatchPageRouteImport
      parentRoute: typeof DashboardAccountsPayableBatchLayoutRoute
    }
    '/dashboard/vendor/batch/$batchId': {
      id: '/dashboard/vendor/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/vendor/batch/$batchId'
      preLoaderRoute: typeof DashboardVendorBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardVendorBatchLayoutRoute
    }
    '/dashboard/ledger/batch/$batchId': {
      id: '/dashboard/ledger/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/ledger/batch/$batchId'
      preLoaderRoute: typeof DashboardLedgerBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardLedgerBatchLayoutRoute
    }
    '/dashboard/cash-out/batch/$batchId': {
      id: '/dashboard/cash-out/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/cash-out/batch/$batchId'
      preLoaderRoute: typeof DashboardCashOutBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardCashOutBatchLayoutRoute
    }
    '/dashboard/cash-management/batch/$batchId': {
      id: '/dashboard/cash-management/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/cash-management/batch/$batchId'
      preLoaderRoute: typeof DashboardCashManagementBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardCashManagementBatchLayoutRoute
    }
    '/dashboard/cash-in/batch/$batchId': {
      id: '/dashboard/cash-in/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/cash-in/batch/$batchId'
      preLoaderRoute: typeof DashboardCashInBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardCashInBatchLayoutRoute
    }
    '/dashboard/accounts-receivable/batch/$batchId': {
      id: '/dashboard/accounts-receivable/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/accounts-receivable/batch/$batchId'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardAccountsReceivableBatchLayoutRoute
    }
    '/dashboard/accounts-payable/batch/$batchId': {
      id: '/dashboard/accounts-payable/batch/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/accounts-payable/batch/$batchId'
      preLoaderRoute: typeof DashboardAccountsPayableBatchBatchIdLayoutRouteImport
      parentRoute: typeof DashboardAccountsPayableBatchLayoutRoute
    }
    '/dashboard/vendor/batch/new/': {
      id: '/dashboard/vendor/batch/new/'
      path: '/new'
      fullPath: '/dashboard/vendor/batch/new'
      preLoaderRoute: typeof DashboardVendorBatchNewPageRouteImport
      parentRoute: typeof DashboardVendorBatchLayoutRoute
    }
    '/dashboard/ledger/batch/new/': {
      id: '/dashboard/ledger/batch/new/'
      path: '/new'
      fullPath: '/dashboard/ledger/batch/new'
      preLoaderRoute: typeof DashboardLedgerBatchNewPageRouteImport
      parentRoute: typeof DashboardLedgerBatchLayoutRoute
    }
    '/dashboard/cash-out/batch/new/': {
      id: '/dashboard/cash-out/batch/new/'
      path: '/new'
      fullPath: '/dashboard/cash-out/batch/new'
      preLoaderRoute: typeof DashboardCashOutBatchNewPageRouteImport
      parentRoute: typeof DashboardCashOutBatchLayoutRoute
    }
    '/dashboard/cash-management/batch/new/': {
      id: '/dashboard/cash-management/batch/new/'
      path: '/new'
      fullPath: '/dashboard/cash-management/batch/new'
      preLoaderRoute: typeof DashboardCashManagementBatchNewPageRouteImport
      parentRoute: typeof DashboardCashManagementBatchLayoutRoute
    }
    '/dashboard/cash-in/batch/new/': {
      id: '/dashboard/cash-in/batch/new/'
      path: '/new'
      fullPath: '/dashboard/cash-in/batch/new'
      preLoaderRoute: typeof DashboardCashInBatchNewPageRouteImport
      parentRoute: typeof DashboardCashInBatchLayoutRoute
    }
    '/dashboard/accounts-receivable/batch/new/': {
      id: '/dashboard/accounts-receivable/batch/new/'
      path: '/new'
      fullPath: '/dashboard/accounts-receivable/batch/new'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchNewPageRouteImport
      parentRoute: typeof DashboardAccountsReceivableBatchLayoutRoute
    }
    '/dashboard/accounts-payable/batch/new/': {
      id: '/dashboard/accounts-payable/batch/new/'
      path: '/new'
      fullPath: '/dashboard/accounts-payable/batch/new'
      preLoaderRoute: typeof DashboardAccountsPayableBatchNewPageRouteImport
      parentRoute: typeof DashboardAccountsPayableBatchLayoutRoute
    }
    '/dashboard/vendor/batch/$batchId/errors/': {
      id: '/dashboard/vendor/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/vendor/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardVendorBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardVendorBatchBatchIdLayoutRoute
    }
    '/dashboard/vendor/batch/$batchId/(view)/': {
      id: '/dashboard/vendor/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/vendor/batch/$batchId/'
      preLoaderRoute: typeof DashboardVendorBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardVendorBatchBatchIdLayoutRoute
    }
    '/dashboard/ledger/batch/$batchId/errors/': {
      id: '/dashboard/ledger/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/ledger/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardLedgerBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardLedgerBatchBatchIdLayoutRoute
    }
    '/dashboard/ledger/batch/$batchId/(view)/': {
      id: '/dashboard/ledger/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/ledger/batch/$batchId/'
      preLoaderRoute: typeof DashboardLedgerBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardLedgerBatchBatchIdLayoutRoute
    }
    '/dashboard/cash-out/batch/$batchId/errors/': {
      id: '/dashboard/cash-out/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/cash-out/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardCashOutBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardCashOutBatchBatchIdLayoutRoute
    }
    '/dashboard/cash-out/batch/$batchId/(view)/': {
      id: '/dashboard/cash-out/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/cash-out/batch/$batchId/'
      preLoaderRoute: typeof DashboardCashOutBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardCashOutBatchBatchIdLayoutRoute
    }
    '/dashboard/cash-management/batch/$batchId/errors/': {
      id: '/dashboard/cash-management/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/cash-management/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardCashManagementBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardCashManagementBatchBatchIdLayoutRoute
    }
    '/dashboard/cash-management/batch/$batchId/(view)/': {
      id: '/dashboard/cash-management/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/cash-management/batch/$batchId/'
      preLoaderRoute: typeof DashboardCashManagementBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardCashManagementBatchBatchIdLayoutRoute
    }
    '/dashboard/cash-in/batch/$batchId/errors/': {
      id: '/dashboard/cash-in/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/cash-in/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardCashInBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardCashInBatchBatchIdLayoutRoute
    }
    '/dashboard/cash-in/batch/$batchId/(view)/': {
      id: '/dashboard/cash-in/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/cash-in/batch/$batchId/'
      preLoaderRoute: typeof DashboardCashInBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardCashInBatchBatchIdLayoutRoute
    }
    '/dashboard/accounts-receivable/batch/$batchId/errors/': {
      id: '/dashboard/accounts-receivable/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/accounts-receivable/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutRoute
    }
    '/dashboard/accounts-receivable/batch/$batchId/(view)/': {
      id: '/dashboard/accounts-receivable/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/accounts-receivable/batch/$batchId/'
      preLoaderRoute: typeof DashboardAccountsReceivableBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutRoute
    }
    '/dashboard/accounts-payable/batch/$batchId/errors/': {
      id: '/dashboard/accounts-payable/batch/$batchId/errors/'
      path: '/errors'
      fullPath: '/dashboard/accounts-payable/batch/$batchId/errors'
      preLoaderRoute: typeof DashboardAccountsPayableBatchBatchIdErrorsPageRouteImport
      parentRoute: typeof DashboardAccountsPayableBatchBatchIdLayoutRoute
    }
    '/dashboard/accounts-payable/batch/$batchId/(view)/': {
      id: '/dashboard/accounts-payable/batch/$batchId/(view)/'
      path: '/'
      fullPath: '/dashboard/accounts-payable/batch/$batchId/'
      preLoaderRoute: typeof DashboardAccountsPayableBatchBatchIdviewPageRouteImport
      parentRoute: typeof DashboardAccountsPayableBatchBatchIdLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginPageRoute: typeof AuthLoginPageRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginPageRoute: AuthLoginPageRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublichomePageRoute: typeof PublichomePageRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublichomePageRoute: PublichomePageRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface DashboardAccountsPayableBatchBatchIdLayoutRouteChildren {
  DashboardAccountsPayableBatchBatchIdviewPageRoute: typeof DashboardAccountsPayableBatchBatchIdviewPageRoute
  DashboardAccountsPayableBatchBatchIdErrorsPageRoute: typeof DashboardAccountsPayableBatchBatchIdErrorsPageRoute
}

const DashboardAccountsPayableBatchBatchIdLayoutRouteChildren: DashboardAccountsPayableBatchBatchIdLayoutRouteChildren =
  {
    DashboardAccountsPayableBatchBatchIdviewPageRoute:
      DashboardAccountsPayableBatchBatchIdviewPageRoute,
    DashboardAccountsPayableBatchBatchIdErrorsPageRoute:
      DashboardAccountsPayableBatchBatchIdErrorsPageRoute,
  }

const DashboardAccountsPayableBatchBatchIdLayoutRouteWithChildren =
  DashboardAccountsPayableBatchBatchIdLayoutRoute._addFileChildren(
    DashboardAccountsPayableBatchBatchIdLayoutRouteChildren,
  )

interface DashboardAccountsPayableBatchLayoutRouteChildren {
  DashboardAccountsPayableBatchBatchIdLayoutRoute: typeof DashboardAccountsPayableBatchBatchIdLayoutRouteWithChildren
  DashboardAccountsPayableBatchPageRoute: typeof DashboardAccountsPayableBatchPageRoute
  DashboardAccountsPayableBatchNewPageRoute: typeof DashboardAccountsPayableBatchNewPageRoute
}

const DashboardAccountsPayableBatchLayoutRouteChildren: DashboardAccountsPayableBatchLayoutRouteChildren =
  {
    DashboardAccountsPayableBatchBatchIdLayoutRoute:
      DashboardAccountsPayableBatchBatchIdLayoutRouteWithChildren,
    DashboardAccountsPayableBatchPageRoute:
      DashboardAccountsPayableBatchPageRoute,
    DashboardAccountsPayableBatchNewPageRoute:
      DashboardAccountsPayableBatchNewPageRoute,
  }

const DashboardAccountsPayableBatchLayoutRouteWithChildren =
  DashboardAccountsPayableBatchLayoutRoute._addFileChildren(
    DashboardAccountsPayableBatchLayoutRouteChildren,
  )

interface DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren {
  DashboardAccountsReceivableBatchBatchIdviewPageRoute: typeof DashboardAccountsReceivableBatchBatchIdviewPageRoute
  DashboardAccountsReceivableBatchBatchIdErrorsPageRoute: typeof DashboardAccountsReceivableBatchBatchIdErrorsPageRoute
}

const DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren: DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren =
  {
    DashboardAccountsReceivableBatchBatchIdviewPageRoute:
      DashboardAccountsReceivableBatchBatchIdviewPageRoute,
    DashboardAccountsReceivableBatchBatchIdErrorsPageRoute:
      DashboardAccountsReceivableBatchBatchIdErrorsPageRoute,
  }

const DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren =
  DashboardAccountsReceivableBatchBatchIdLayoutRoute._addFileChildren(
    DashboardAccountsReceivableBatchBatchIdLayoutRouteChildren,
  )

interface DashboardAccountsReceivableBatchLayoutRouteChildren {
  DashboardAccountsReceivableBatchBatchIdLayoutRoute: typeof DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren
  DashboardAccountsReceivableBatchPageRoute: typeof DashboardAccountsReceivableBatchPageRoute
  DashboardAccountsReceivableBatchNewPageRoute: typeof DashboardAccountsReceivableBatchNewPageRoute
}

const DashboardAccountsReceivableBatchLayoutRouteChildren: DashboardAccountsReceivableBatchLayoutRouteChildren =
  {
    DashboardAccountsReceivableBatchBatchIdLayoutRoute:
      DashboardAccountsReceivableBatchBatchIdLayoutRouteWithChildren,
    DashboardAccountsReceivableBatchPageRoute:
      DashboardAccountsReceivableBatchPageRoute,
    DashboardAccountsReceivableBatchNewPageRoute:
      DashboardAccountsReceivableBatchNewPageRoute,
  }

const DashboardAccountsReceivableBatchLayoutRouteWithChildren =
  DashboardAccountsReceivableBatchLayoutRoute._addFileChildren(
    DashboardAccountsReceivableBatchLayoutRouteChildren,
  )

interface DashboardCashInBatchBatchIdLayoutRouteChildren {
  DashboardCashInBatchBatchIdviewPageRoute: typeof DashboardCashInBatchBatchIdviewPageRoute
  DashboardCashInBatchBatchIdErrorsPageRoute: typeof DashboardCashInBatchBatchIdErrorsPageRoute
}

const DashboardCashInBatchBatchIdLayoutRouteChildren: DashboardCashInBatchBatchIdLayoutRouteChildren =
  {
    DashboardCashInBatchBatchIdviewPageRoute:
      DashboardCashInBatchBatchIdviewPageRoute,
    DashboardCashInBatchBatchIdErrorsPageRoute:
      DashboardCashInBatchBatchIdErrorsPageRoute,
  }

const DashboardCashInBatchBatchIdLayoutRouteWithChildren =
  DashboardCashInBatchBatchIdLayoutRoute._addFileChildren(
    DashboardCashInBatchBatchIdLayoutRouteChildren,
  )

interface DashboardCashInBatchLayoutRouteChildren {
  DashboardCashInBatchBatchIdLayoutRoute: typeof DashboardCashInBatchBatchIdLayoutRouteWithChildren
  DashboardCashInBatchPageRoute: typeof DashboardCashInBatchPageRoute
  DashboardCashInBatchNewPageRoute: typeof DashboardCashInBatchNewPageRoute
}

const DashboardCashInBatchLayoutRouteChildren: DashboardCashInBatchLayoutRouteChildren =
  {
    DashboardCashInBatchBatchIdLayoutRoute:
      DashboardCashInBatchBatchIdLayoutRouteWithChildren,
    DashboardCashInBatchPageRoute: DashboardCashInBatchPageRoute,
    DashboardCashInBatchNewPageRoute: DashboardCashInBatchNewPageRoute,
  }

const DashboardCashInBatchLayoutRouteWithChildren =
  DashboardCashInBatchLayoutRoute._addFileChildren(
    DashboardCashInBatchLayoutRouteChildren,
  )

interface DashboardCashManagementBatchBatchIdLayoutRouteChildren {
  DashboardCashManagementBatchBatchIdviewPageRoute: typeof DashboardCashManagementBatchBatchIdviewPageRoute
  DashboardCashManagementBatchBatchIdErrorsPageRoute: typeof DashboardCashManagementBatchBatchIdErrorsPageRoute
}

const DashboardCashManagementBatchBatchIdLayoutRouteChildren: DashboardCashManagementBatchBatchIdLayoutRouteChildren =
  {
    DashboardCashManagementBatchBatchIdviewPageRoute:
      DashboardCashManagementBatchBatchIdviewPageRoute,
    DashboardCashManagementBatchBatchIdErrorsPageRoute:
      DashboardCashManagementBatchBatchIdErrorsPageRoute,
  }

const DashboardCashManagementBatchBatchIdLayoutRouteWithChildren =
  DashboardCashManagementBatchBatchIdLayoutRoute._addFileChildren(
    DashboardCashManagementBatchBatchIdLayoutRouteChildren,
  )

interface DashboardCashManagementBatchLayoutRouteChildren {
  DashboardCashManagementBatchBatchIdLayoutRoute: typeof DashboardCashManagementBatchBatchIdLayoutRouteWithChildren
  DashboardCashManagementBatchPageRoute: typeof DashboardCashManagementBatchPageRoute
  DashboardCashManagementBatchNewPageRoute: typeof DashboardCashManagementBatchNewPageRoute
}

const DashboardCashManagementBatchLayoutRouteChildren: DashboardCashManagementBatchLayoutRouteChildren =
  {
    DashboardCashManagementBatchBatchIdLayoutRoute:
      DashboardCashManagementBatchBatchIdLayoutRouteWithChildren,
    DashboardCashManagementBatchPageRoute:
      DashboardCashManagementBatchPageRoute,
    DashboardCashManagementBatchNewPageRoute:
      DashboardCashManagementBatchNewPageRoute,
  }

const DashboardCashManagementBatchLayoutRouteWithChildren =
  DashboardCashManagementBatchLayoutRoute._addFileChildren(
    DashboardCashManagementBatchLayoutRouteChildren,
  )

interface DashboardCashOutBatchBatchIdLayoutRouteChildren {
  DashboardCashOutBatchBatchIdviewPageRoute: typeof DashboardCashOutBatchBatchIdviewPageRoute
  DashboardCashOutBatchBatchIdErrorsPageRoute: typeof DashboardCashOutBatchBatchIdErrorsPageRoute
}

const DashboardCashOutBatchBatchIdLayoutRouteChildren: DashboardCashOutBatchBatchIdLayoutRouteChildren =
  {
    DashboardCashOutBatchBatchIdviewPageRoute:
      DashboardCashOutBatchBatchIdviewPageRoute,
    DashboardCashOutBatchBatchIdErrorsPageRoute:
      DashboardCashOutBatchBatchIdErrorsPageRoute,
  }

const DashboardCashOutBatchBatchIdLayoutRouteWithChildren =
  DashboardCashOutBatchBatchIdLayoutRoute._addFileChildren(
    DashboardCashOutBatchBatchIdLayoutRouteChildren,
  )

interface DashboardCashOutBatchLayoutRouteChildren {
  DashboardCashOutBatchBatchIdLayoutRoute: typeof DashboardCashOutBatchBatchIdLayoutRouteWithChildren
  DashboardCashOutBatchPageRoute: typeof DashboardCashOutBatchPageRoute
  DashboardCashOutBatchNewPageRoute: typeof DashboardCashOutBatchNewPageRoute
}

const DashboardCashOutBatchLayoutRouteChildren: DashboardCashOutBatchLayoutRouteChildren =
  {
    DashboardCashOutBatchBatchIdLayoutRoute:
      DashboardCashOutBatchBatchIdLayoutRouteWithChildren,
    DashboardCashOutBatchPageRoute: DashboardCashOutBatchPageRoute,
    DashboardCashOutBatchNewPageRoute: DashboardCashOutBatchNewPageRoute,
  }

const DashboardCashOutBatchLayoutRouteWithChildren =
  DashboardCashOutBatchLayoutRoute._addFileChildren(
    DashboardCashOutBatchLayoutRouteChildren,
  )

interface DashboardLedgerBatchBatchIdLayoutRouteChildren {
  DashboardLedgerBatchBatchIdviewPageRoute: typeof DashboardLedgerBatchBatchIdviewPageRoute
  DashboardLedgerBatchBatchIdErrorsPageRoute: typeof DashboardLedgerBatchBatchIdErrorsPageRoute
}

const DashboardLedgerBatchBatchIdLayoutRouteChildren: DashboardLedgerBatchBatchIdLayoutRouteChildren =
  {
    DashboardLedgerBatchBatchIdviewPageRoute:
      DashboardLedgerBatchBatchIdviewPageRoute,
    DashboardLedgerBatchBatchIdErrorsPageRoute:
      DashboardLedgerBatchBatchIdErrorsPageRoute,
  }

const DashboardLedgerBatchBatchIdLayoutRouteWithChildren =
  DashboardLedgerBatchBatchIdLayoutRoute._addFileChildren(
    DashboardLedgerBatchBatchIdLayoutRouteChildren,
  )

interface DashboardLedgerBatchLayoutRouteChildren {
  DashboardLedgerBatchBatchIdLayoutRoute: typeof DashboardLedgerBatchBatchIdLayoutRouteWithChildren
  DashboardLedgerBatchPageRoute: typeof DashboardLedgerBatchPageRoute
  DashboardLedgerBatchNewPageRoute: typeof DashboardLedgerBatchNewPageRoute
}

const DashboardLedgerBatchLayoutRouteChildren: DashboardLedgerBatchLayoutRouteChildren =
  {
    DashboardLedgerBatchBatchIdLayoutRoute:
      DashboardLedgerBatchBatchIdLayoutRouteWithChildren,
    DashboardLedgerBatchPageRoute: DashboardLedgerBatchPageRoute,
    DashboardLedgerBatchNewPageRoute: DashboardLedgerBatchNewPageRoute,
  }

const DashboardLedgerBatchLayoutRouteWithChildren =
  DashboardLedgerBatchLayoutRoute._addFileChildren(
    DashboardLedgerBatchLayoutRouteChildren,
  )

interface DashboardVendorBatchBatchIdLayoutRouteChildren {
  DashboardVendorBatchBatchIdviewPageRoute: typeof DashboardVendorBatchBatchIdviewPageRoute
  DashboardVendorBatchBatchIdErrorsPageRoute: typeof DashboardVendorBatchBatchIdErrorsPageRoute
}

const DashboardVendorBatchBatchIdLayoutRouteChildren: DashboardVendorBatchBatchIdLayoutRouteChildren =
  {
    DashboardVendorBatchBatchIdviewPageRoute:
      DashboardVendorBatchBatchIdviewPageRoute,
    DashboardVendorBatchBatchIdErrorsPageRoute:
      DashboardVendorBatchBatchIdErrorsPageRoute,
  }

const DashboardVendorBatchBatchIdLayoutRouteWithChildren =
  DashboardVendorBatchBatchIdLayoutRoute._addFileChildren(
    DashboardVendorBatchBatchIdLayoutRouteChildren,
  )

interface DashboardVendorBatchLayoutRouteChildren {
  DashboardVendorBatchBatchIdLayoutRoute: typeof DashboardVendorBatchBatchIdLayoutRouteWithChildren
  DashboardVendorBatchNewPageRoute: typeof DashboardVendorBatchNewPageRoute
}

const DashboardVendorBatchLayoutRouteChildren: DashboardVendorBatchLayoutRouteChildren =
  {
    DashboardVendorBatchBatchIdLayoutRoute:
      DashboardVendorBatchBatchIdLayoutRouteWithChildren,
    DashboardVendorBatchNewPageRoute: DashboardVendorBatchNewPageRoute,
  }

const DashboardVendorBatchLayoutRouteWithChildren =
  DashboardVendorBatchLayoutRoute._addFileChildren(
    DashboardVendorBatchLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardAccountsPayableBatchLayoutRoute: typeof DashboardAccountsPayableBatchLayoutRouteWithChildren
  DashboardAccountsReceivableBatchLayoutRoute: typeof DashboardAccountsReceivableBatchLayoutRouteWithChildren
  DashboardCashInBatchLayoutRoute: typeof DashboardCashInBatchLayoutRouteWithChildren
  DashboardCashManagementBatchLayoutRoute: typeof DashboardCashManagementBatchLayoutRouteWithChildren
  DashboardCashOutBatchLayoutRoute: typeof DashboardCashOutBatchLayoutRouteWithChildren
  DashboardLedgerBatchLayoutRoute: typeof DashboardLedgerBatchLayoutRouteWithChildren
  DashboardVendorBatchLayoutRoute: typeof DashboardVendorBatchLayoutRouteWithChildren
  DashboardhomePageRoute: typeof DashboardhomePageRoute
  DashboardAccountsPayablePageRoute: typeof DashboardAccountsPayablePageRoute
  DashboardAccountsReceivablePageRoute: typeof DashboardAccountsReceivablePageRoute
  DashboardCashInPageRoute: typeof DashboardCashInPageRoute
  DashboardCashManagementPageRoute: typeof DashboardCashManagementPageRoute
  DashboardCashOutPageRoute: typeof DashboardCashOutPageRoute
  DashboardLedgerPageRoute: typeof DashboardLedgerPageRoute
  DashboardSettingsPageRoute: typeof DashboardSettingsPageRoute
  DashboardVendorPageRoute: typeof DashboardVendorPageRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardAccountsPayableBatchLayoutRoute:
    DashboardAccountsPayableBatchLayoutRouteWithChildren,
  DashboardAccountsReceivableBatchLayoutRoute:
    DashboardAccountsReceivableBatchLayoutRouteWithChildren,
  DashboardCashInBatchLayoutRoute: DashboardCashInBatchLayoutRouteWithChildren,
  DashboardCashManagementBatchLayoutRoute:
    DashboardCashManagementBatchLayoutRouteWithChildren,
  DashboardCashOutBatchLayoutRoute:
    DashboardCashOutBatchLayoutRouteWithChildren,
  DashboardLedgerBatchLayoutRoute: DashboardLedgerBatchLayoutRouteWithChildren,
  DashboardVendorBatchLayoutRoute: DashboardVendorBatchLayoutRouteWithChildren,
  DashboardhomePageRoute: DashboardhomePageRoute,
  DashboardAccountsPayablePageRoute: DashboardAccountsPayablePageRoute,
  DashboardAccountsReceivablePageRoute: DashboardAccountsReceivablePageRoute,
  DashboardCashInPageRoute: DashboardCashInPageRoute,
  DashboardCashManagementPageRoute: DashboardCashManagementPageRoute,
  DashboardCashOutPageRoute: DashboardCashOutPageRoute,
  DashboardLedgerPageRoute: DashboardLedgerPageRoute,
  DashboardSettingsPageRoute: DashboardSettingsPageRoute,
  DashboardVendorPageRoute: DashboardVendorPageRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
